import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (user?.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 });
    const s = base44.asServiceRole;

    await s.entities.ClientPerformanceMetric.bulkCreate([
      { company_name: 'Arctic Air HVAC', vertical: 'HVAC', revenue_tier: 'professional', roi_score: 91, growth_momentum: 'accelerating', ranking_trend: 'improving', social_reach_trend: 'up', lead_signal_strength: 'strong', roi_confidence: 94, content_cadence_score: 88, video_performance_score: 92, engagement_velocity: 42, keywords_improved: 18, social_reach_growth_pct: 42, estimated_leads_month: 42, mrr: 2400, city: 'Denver', state: 'CO', upsell_probability: 82, churn_risk_score: 8, account_manager: 'Sarah M.' },
      { company_name: 'ProHeat Systems', vertical: 'HVAC', revenue_tier: 'growth', roi_score: 84, growth_momentum: 'accelerating', ranking_trend: 'improving', social_reach_trend: 'up', lead_signal_strength: 'strong', roi_confidence: 88, content_cadence_score: 82, video_performance_score: 86, engagement_velocity: 31, keywords_improved: 12, social_reach_growth_pct: 31, estimated_leads_month: 29, mrr: 1800, city: 'Dallas', state: 'TX', upsell_probability: 74, churn_risk_score: 14, account_manager: 'Mike D.' },
      { company_name: 'Mesa Grill Group', vertical: 'Restaurant', revenue_tier: 'growth', roi_score: 71, growth_momentum: 'stable', ranking_trend: 'stable', social_reach_trend: 'up', lead_signal_strength: 'moderate', roi_confidence: 74, content_cadence_score: 72, video_performance_score: 78, engagement_velocity: 18, keywords_improved: 6, social_reach_growth_pct: 18, estimated_leads_month: 18, mrr: 1600, city: 'Phoenix', state: 'AZ', upsell_probability: 58, churn_risk_score: 24, account_manager: 'Sarah M.' },
      { company_name: 'Precision Plumbing', vertical: 'Home Services', revenue_tier: 'professional', roi_score: 88, growth_momentum: 'accelerating', ranking_trend: 'improving', social_reach_trend: 'up', lead_signal_strength: 'strong', roi_confidence: 91, content_cadence_score: 86, video_performance_score: 84, engagement_velocity: 38, keywords_improved: 22, social_reach_growth_pct: 38, estimated_leads_month: 38, mrr: 2200, city: 'Charlotte', state: 'NC', upsell_probability: 87, churn_risk_score: 9, account_manager: 'James K.' },
      { company_name: 'Taco Loco Franchise', vertical: 'Restaurant', revenue_tier: 'starter', roi_score: 62, growth_momentum: 'stable', ranking_trend: 'stable', social_reach_trend: 'stable', lead_signal_strength: 'moderate', roi_confidence: 66, content_cadence_score: 64, video_performance_score: 68, engagement_velocity: 9, keywords_improved: 4, social_reach_growth_pct: 9, estimated_leads_month: 14, mrr: 900, city: 'Austin', state: 'TX', upsell_probability: 42, churn_risk_score: 38, account_manager: 'Mike D.' },
      { company_name: 'Blue Ridge Roofing', vertical: 'Home Services', revenue_tier: 'growth', roi_score: 48, growth_momentum: 'declining', ranking_trend: 'declining', social_reach_trend: 'down', lead_signal_strength: 'weak', roi_confidence: 42, content_cadence_score: 38, video_performance_score: 44, engagement_velocity: -12, keywords_improved: -3, social_reach_growth_pct: -12, estimated_leads_month: 11, mrr: 1400, city: 'Asheville', state: 'NC', upsell_probability: 18, churn_risk_score: 58, account_manager: 'James K.' },
      { company_name: 'Apex Law Partners', vertical: 'Legal', revenue_tier: 'enterprise', roi_score: 78, growth_momentum: 'stable', ranking_trend: 'improving', social_reach_trend: 'stable', lead_signal_strength: 'moderate', roi_confidence: 80, content_cadence_score: 76, video_performance_score: 74, engagement_velocity: 14, keywords_improved: 9, social_reach_growth_pct: 14, estimated_leads_month: 22, mrr: 3200, city: 'Chicago', state: 'IL', upsell_probability: 82, churn_risk_score: 12, account_manager: 'Sarah M.' },
      { company_name: 'Citywide Dental', vertical: 'Dental', revenue_tier: 'growth', roi_score: 85, growth_momentum: 'accelerating', ranking_trend: 'improving', social_reach_trend: 'up', lead_signal_strength: 'strong', roi_confidence: 87, content_cadence_score: 84, video_performance_score: 90, engagement_velocity: 27, keywords_improved: 14, social_reach_growth_pct: 27, estimated_leads_month: 34, mrr: 1900, city: 'Orlando', state: 'FL', upsell_probability: 78, churn_risk_score: 11, account_manager: 'Mike D.' },
      { company_name: 'CoolBreeze HVAC', vertical: 'HVAC', revenue_tier: 'starter', roi_score: 44, growth_momentum: 'declining', ranking_trend: 'declining', social_reach_trend: 'down', lead_signal_strength: 'weak', roi_confidence: 38, content_cadence_score: 32, video_performance_score: 38, engagement_velocity: -18, keywords_improved: -5, social_reach_growth_pct: -18, estimated_leads_month: 8, mrr: 800, city: 'Tampa', state: 'FL', upsell_probability: 12, churn_risk_score: 72, account_manager: 'James K.' },
    ]);

    await s.entities.UpsellOpportunitySignal.bulkCreate([
      { client_name: 'Arctic Air HVAC', vertical: 'HVAC', opportunity_type: 'premium_video', status: 'detected', projected_added_mrr: 800, confidence_score: 91, recommended_package: 'Video Authority Pack Pro', urgency: 'high', current_mrr: 2400, trigger_signal: 'Social video content achieving 3x avg engagement', detected_date: '2026-03-10' },
      { client_name: 'Precision Plumbing', vertical: 'Home Services', opportunity_type: 'multi_location', status: 'detected', projected_added_mrr: 1200, confidence_score: 87, recommended_package: 'Multi-Location Growth', urgency: 'high', current_mrr: 2200, trigger_signal: 'Owner mentioned second location in last strategy call', detected_date: '2026-03-08' },
      { client_name: 'Apex Law Partners', vertical: 'Legal', opportunity_type: 'authority_pack', status: 'outreach_sent', projected_added_mrr: 600, confidence_score: 82, recommended_package: 'Legal Authority Pack', urgency: 'medium', current_mrr: 3200, trigger_signal: 'Consistent top-3 rankings — reputation management upsell ready', detected_date: '2026-03-05' },
      { client_name: 'Citywide Dental', vertical: 'Dental', opportunity_type: 'streaming_tv', status: 'detected', projected_added_mrr: 900, confidence_score: 78, recommended_package: 'Streaming TV Starter', urgency: 'medium', current_mrr: 1900, trigger_signal: 'Video content performance above 85th percentile', detected_date: '2026-03-11' },
      { client_name: 'ProHeat Systems', vertical: 'HVAC', opportunity_type: 'annual_prepay', status: 'detected', projected_added_mrr: 320, confidence_score: 88, recommended_package: 'Annual Prepay 20% Discount', urgency: 'high', current_mrr: 1800, trigger_signal: '6-month streak of positive performance signals', detected_date: '2026-03-12' },
    ]);

    await s.entities.RetentionRiskSignal.bulkCreate([
      { client_name: 'CoolBreeze HVAC', vertical: 'HVAC', churn_probability: 72, risk_level: 'critical', declining_content_output: true, falling_engagement: true, ranking_stagnation: true, low_login_activity: false, negative_satisfaction: false, primary_signal: 'Content production stalled 3 weeks, engagement down 44%', days_until_renewal: 28, mrr: 800, intervention_status: 'none', assigned_manager: 'James K.' },
      { client_name: 'Blue Ridge Roofing', vertical: 'Home Services', churn_probability: 58, risk_level: 'high', declining_content_output: true, falling_engagement: false, ranking_stagnation: true, low_login_activity: true, negative_satisfaction: false, primary_signal: 'Missing seasonal campaign window — login activity near zero', days_until_renewal: 45, mrr: 1400, intervention_status: 'none', assigned_manager: 'James K.' },
      { client_name: 'Taco Loco Franchise', vertical: 'Restaurant', churn_probability: 38, risk_level: 'medium', declining_content_output: false, falling_engagement: true, ranking_stagnation: false, low_login_activity: true, negative_satisfaction: false, primary_signal: 'Engagement slipping — approval delays increasing', days_until_renewal: 62, mrr: 900, intervention_status: 'triggered', assigned_manager: 'Mike D.' },
    ]);

    await s.entities.PerformanceTimelineEvent.bulkCreate([
      { client_name: 'Arctic Air HVAC', vertical: 'HVAC', revenue_tier: 'professional', city: 'Denver', state: 'CO', event_type: 'ranking_breakthrough', event_date: '2026-03-10', headline: '18 keywords moved to top 5 — spring SEO surge', description: 'Dominant local visibility achieved in Denver metro for AC installation and emergency HVAC terms.', milestone: true, mrr_at_event: 2400 },
      { client_name: 'Citywide Dental', vertical: 'Dental', revenue_tier: 'growth', city: 'Orlando', state: 'FL', event_type: 'viral_post', event_date: '2026-03-08', headline: 'Instagram Reel hit 38K reach in 48 hours', description: '"Same-day crown" demo video went viral in Orlando dental market.', milestone: true, mrr_at_event: 1900 },
      { client_name: 'Precision Plumbing', vertical: 'Home Services', revenue_tier: 'professional', city: 'Charlotte', state: 'NC', event_type: 'upsell_accepted', event_date: '2026-03-06', headline: 'Accepted multi-location expansion package', description: 'Signed second location upgrade. MRR increasing to $3,400.', milestone: true, mrr_at_event: 2200 },
      { client_name: 'CoolBreeze HVAC', vertical: 'HVAC', revenue_tier: 'starter', city: 'Tampa', state: 'FL', event_type: 'risk_flagged', event_date: '2026-02-28', headline: 'Performance decline flagged — retention intervention needed', description: 'Content production paused. Engagement down 44%. Churn risk elevated to critical.', milestone: false, mrr_at_event: 800 },
      { client_name: 'Apex Law Partners', vertical: 'Legal', revenue_tier: 'enterprise', city: 'Chicago', state: 'IL', event_type: 'renewal_milestone', event_date: '2026-02-22', headline: 'Renewed annual contract — year 2 milestone', description: 'Strong ROI documentation supported renewal. Client noted 3x estimated lead growth.', milestone: true, mrr_at_event: 3200 },
    ]);

    await s.entities.ROIInsight.bulkCreate([
      { insight_type: 'roi_curve', headline: 'HVAC clients achieving fastest ROI curve in portfolio', narrative: 'Arctic Air and ProHeat are on a 94-day average time-to-positive-ROI — 38% faster than the rest of the portfolio.', severity: 'info', status: 'new', related_vertical: 'HVAC', impact_estimate: '+$4,200 avg LTV' },
      { insight_type: 'content_performance', headline: 'Video-first campaigns producing 2x engagement vs. written content', narrative: 'Across 9 active clients, video assets generate 2.1x higher social engagement and 1.6x higher CTR than article-only campaigns.', severity: 'info', status: 'new', impact_estimate: 'Portfolio engagement +34%' },
      { insight_type: 'pricing_opportunity', headline: 'Opportunity to reposition 4 clients to higher pricing tier', narrative: 'Arctic Air, Precision Plumbing, Citywide Dental, and Apex Law are performing at enterprise-level output while on lower plans.', severity: 'high', status: 'new', impact_estimate: '+$1,800 MRR potential' },
      { insight_type: 'churn_signal', headline: 'Two clients entering critical churn risk window', narrative: 'CoolBreeze and Blue Ridge showing compounding negative signals. Combined MRR at risk: $2,200. Intervention window closing within 30 days.', severity: 'critical', status: 'new', related_vertical: 'HVAC / Roofing', impact_estimate: '$2,200 MRR at risk' },
    ]);

    return Response.json({ success: true, message: 'Client Performance Command Center seeded!' });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});