import React, { useState } from 'react';
import { X, ChevronRight, ChevronLeft, ExternalLink } from 'lucide-react';
import NTAGuideAvatar from './NTAGuideAvatar';
import { Link } from 'react-router-dom';

const TOUR_STEPS = [
  {
    id: 'authority_system',
    title: 'The Authority System Framework',
    emoji: '🏗️',
    body: `NTA isn't a set of tools — it's a unified growth engine. Your authority website, AI content, streaming visibility, and automated publishing all operate as one coordinated system.`,
    highlight: 'Unlike agencies that sell hours, the NTA platform sells outcomes. Every component is designed to compound authority over time.',
    color: '#3b82f6',
  },
  {
    id: 'streaming',
    title: 'Streaming TV Visibility',
    emoji: '📺',
    body: `Your business appears on Roku, Amazon Fire TV, and Apple TV — reaching local audiences in your service area while they're watching TV at home.`,
    highlight: 'Most local businesses have zero streaming presence. First-mover advantage in your market is still available in most cities.',
    color: '#06b6d4',
  },
  {
    id: 'ai_content',
    title: 'AI Content Engine',
    emoji: '🤖',
    body: `Every week, the AI engine writes 2 SEO-optimized blogs, 5 social posts, and 1 video script — all branded to your business voice and localized to your city.`,
    highlight: 'That's 400+ pieces of content per year, published automatically. No agency, no freelancer, no effort on your end.',
    color: '#8b5cf6',
  },
  {
    id: 'roi',
    title: 'ROI Reporting & Attribution',
    emoji: '📊',
    body: `Monthly authority reports show your visibility score growth, leads generated by channel, and estimated revenue impact — all connected to the content and campaigns running on your behalf.`,
    highlight: 'You'll know exactly which marketing activities are generating calls and revenue — not just traffic.',
    color: '#10b981',
  },
  {
    id: 'cta',
    title: 'Ready to See It Live?',
    emoji: '🚀',
    body: `The best way to understand the platform is to see it built around your business — your industry, your city, your competitors.`,
    highlight: 'A 30-minute strategy session is free, zero-pressure, and custom-built for your market.',
    color: '#f59e0b',
    isCTA: true,
  },
];

const CLIENT_TIPS = [
  { title: 'Content Approvals', body: 'Review this week\'s scheduled content before it publishes. Your approval takes 30 seconds.', link: '/client/approvals', linkLabel: 'Go to Approvals' },
  { title: 'Channel Connections', body: 'Make sure your social channels are connected so content publishes automatically.', link: '/nta/channels', linkLabel: 'Check Channels' },
  { title: 'Monthly ROI Report', body: 'Your latest performance report is ready — see what\'s driving growth this month.', link: '/client/roi-reports', linkLabel: 'View Report' },
];

const FUNNEL_TIPS = [
  { title: 'What Is a Strategy Session?', body: 'A 30-minute live demo built around your specific market. No generic slides — we show your actual competitors and opportunities.' },
  { title: 'What Does Visibility Gap Mean?', body: 'The difference between how visible you are online today versus the maximum potential for your industry and city.' },
  { title: 'How Fast Does It Work?', body: 'Most clients see measurable visibility improvement within 60 days. Full authority positioning typically takes 4–6 months.' },
];

export default function NTAGuidePanel({ mode = 'homepage', onClose }) {
  const [view, setView] = useState('tour'); // 'tour' | 'tips'
  const [tourStep, setTourStep] = useState(0);

  const step = TOUR_STEPS[tourStep];
  const isLast = tourStep === TOUR_STEPS.length - 1;

  const tips = mode === 'client' ? CLIENT_TIPS : FUNNEL_TIPS;

  return (
    <div className="flex flex-col h-full bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden"
      style={{ width: 360, maxHeight: 580 }}>

      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3.5 bg-gradient-to-r from-blue-700 to-blue-600 flex-shrink-0">
        <NTAGuideAvatar size={34} />
        <div className="flex-1">
          <p className="text-white font-black text-sm">NTA Growth Guide</p>
          <p className="text-blue-200 text-xs">Here to help · Always available</p>
        </div>
        <button onClick={onClose} className="text-blue-200 hover:text-white transition-colors">
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Tab bar — homepage/funnel only */}
      {mode !== 'client' && (
        <div className="flex border-b border-slate-100 flex-shrink-0">
          <button onClick={() => setView('tour')}
            className={`flex-1 py-2.5 text-xs font-bold transition-colors ${view === 'tour' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600'}`}>
            Platform Tour
          </button>
          <button onClick={() => setView('tips')}
            className={`flex-1 py-2.5 text-xs font-bold transition-colors ${view === 'tips' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600'}`}>
            {mode === 'funnel' ? 'Quick Answers' : 'Quick Links'}
          </button>
        </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">

        {/* Tour view */}
        {(view === 'tour' || mode === 'client') && mode !== 'client' && (
          <div>
            {/* Progress dots */}
            <div className="flex items-center gap-1.5 mb-4">
              {TOUR_STEPS.map((_, i) => (
                <button key={i} onClick={() => setTourStep(i)}
                  className={`transition-all rounded-full ${i === tourStep ? 'w-5 h-2 bg-blue-600' : 'w-2 h-2 bg-slate-200 hover:bg-slate-300'}`} />
              ))}
            </div>

            {/* Step card */}
            <div key={step.id} className="animate-in fade-in slide-in-from-right-2 duration-200">
              <div className="flex items-center gap-2.5 mb-3">
                <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg flex-shrink-0"
                  style={{ background: `${step.color}15` }}>
                  {step.emoji}
                </div>
                <h3 className="text-slate-900 font-black text-sm leading-tight">{step.title}</h3>
              </div>

              <p className="text-slate-600 text-sm leading-relaxed mb-3">{step.body}</p>

              <div className="p-3 rounded-xl text-xs leading-relaxed font-medium" style={{ background: `${step.color}10`, color: step.color }}>
                {step.highlight}
              </div>

              {step.isCTA && (
                <Link to="/nta/demo" onClick={onClose}
                  className="mt-4 flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-black text-white bg-blue-600 hover:bg-blue-700 transition-colors">
                  Book My Free Strategy Session <ExternalLink className="w-3.5 h-3.5" />
                </Link>
              )}
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between mt-5">
              <button onClick={() => setTourStep(Math.max(0, tourStep - 1))} disabled={tourStep === 0}
                className="flex items-center gap-1 text-xs font-semibold text-slate-400 hover:text-slate-600 disabled:opacity-30 transition-colors">
                <ChevronLeft className="w-3.5 h-3.5" /> Back
              </button>
              <span className="text-slate-300 text-xs">{tourStep + 1} / {TOUR_STEPS.length}</span>
              {!isLast ? (
                <button onClick={() => setTourStep(tourStep + 1)}
                  className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-700 transition-colors">
                  Next <ChevronRight className="w-3.5 h-3.5" />
                </button>
              ) : (
                <Link to="/nta/demo" onClick={onClose} className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-700">
                  Book Demo <ChevronRight className="w-3.5 h-3.5" />
                </Link>
              )}
            </div>
          </div>
        )}

        {/* Client mode — operational reminders */}
        {mode === 'client' && (
          <div className="space-y-3">
            <p className="text-slate-500 text-xs mb-1">Quick actions for today:</p>
            {CLIENT_TIPS.map((tip, i) => (
              <div key={i} className="p-3.5 rounded-xl border border-slate-200 bg-slate-50">
                <p className="text-slate-900 text-sm font-bold mb-1">{tip.title}</p>
                <p className="text-slate-500 text-xs leading-relaxed mb-2.5">{tip.body}</p>
                <Link to={tip.link} onClick={onClose}
                  className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-700 transition-colors">
                  {tip.linkLabel} <ChevronRight className="w-3 h-3" />
                </Link>
              </div>
            ))}
          </div>
        )}

        {/* Tips view */}
        {view === 'tips' && mode !== 'client' && (
          <div className="space-y-3">
            {tips.map((tip, i) => (
              <div key={i} className="p-3.5 rounded-xl border border-slate-200 bg-slate-50">
                <p className="text-slate-900 text-sm font-bold mb-1.5">{tip.title}</p>
                <p className="text-slate-500 text-xs leading-relaxed">{tip.body}</p>
                {tip.link && (
                  <Link to={tip.link} onClick={onClose} className="flex items-center gap-1 text-xs font-bold text-blue-600 mt-2 hover:text-blue-700">
                    {tip.linkLabel} <ChevronRight className="w-3 h-3" />
                  </Link>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-4 py-3 border-t border-slate-100 bg-slate-50 flex-shrink-0 flex items-center justify-between">
        <p className="text-slate-400 text-xs">NTA Authority Platform</p>
        <Link to="/nta/demo" onClick={onClose} className="text-xs font-bold text-blue-600 hover:text-blue-700">
          Book Demo →
        </Link>
      </div>
    </div>
  );
}