// ─── Restaurant Demo Configurations ────────────────────────────────────────
// Swap out config objects to quickly create new restaurant demos.

export const PIZZA_CONFIG = {
  id: 'pizza',
  name: "Marco's Pizzeria",
  tagline: "Handcrafted Pizza. Local Ingredients.",
  headline: "Local Pizza. Easy Ordering. Built to Be Found.",
  subheadline: "Dine in, carry out, or delivery — Marco's is optimized for Google, voice search, and mobile customers in Mason City.",
  cuisine: 'Pizza',
  city: 'Mason City',
  state: 'IA',
  phone: '(641) 555-0192',
  address: '142 S Federal Ave, Mason City, IA 50401',
  hours: 'Mon–Thu 11am–9pm · Fri–Sat 11am–10pm · Sun 12pm–8pm',
  orderUrl: '#order',
  menuUrl: '#menu',
  directionsUrl: 'https://maps.google.com',
  primaryColor: '#dc2626',
  accentColor: '#ea580c',
  heroImage: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=1400&auto=format&fit=crop',
  logo: '🍕',
  rating: 4.8,
  reviewCount: 312,
  description: "Family-owned since 1988. Marco's has been serving Mason City's favorite handcrafted pizzas for over 35 years. Fresh dough daily, local toppings, and a dining room that feels like home.",
  ownerName: "Marco & Elena Ricci",
  ownerStory: "We started Marco's with one oven, a family recipe, and a belief that great pizza brings people together. Today, we're still making every crust by hand.",
  ownerImage: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&auto=format&fit=crop',
  featuredDishes: [
    { name: 'Marco\'s Classic Pepperoni', price: '$16.99', desc: 'Hand-stretched dough, house marinara, whole milk mozzarella, premium pepperoni', image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop', badge: 'Most Popular' },
    { name: 'BBQ Chicken Supreme', price: '$18.99', desc: 'Smoky BBQ base, grilled chicken, red onions, cilantro, extra cheese', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop', badge: null },
    { name: 'Veggie Garden', price: '$15.99', desc: 'Fresh roasted veggies, basil pesto, feta, sun-dried tomatoes', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop', badge: 'Fan Fave' },
    { name: 'The Mason City Meat Lover\'s', price: '$21.99', desc: 'Pepperoni, sausage, ham, bacon, ground beef — the local legend', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop', badge: 'Local Legend' },
  ],
  specials: [
    { day: 'Monday', title: 'Two-for-Tuesday (Monday Preview)', desc: 'Buy one large pizza, get one 50% off', icon: '🎉' },
    { day: 'Wednesday', title: 'Family Night', desc: 'Large pizza + breadsticks + 2-liter for $24.99', icon: '👨‍👩‍👧' },
    { day: 'Friday', title: 'Late Night Slice', desc: 'By-the-slice available after 8pm Fri & Sat', icon: '🌙' },
    { day: 'Weekend', title: 'Sunday Brunch Pizza', desc: 'Eggs, bacon, and cheese on a crispy crust 12–3pm', icon: '🍳' },
  ],
  reviews: [
    { name: 'Sarah M.', rating: 5, text: "Best pizza in North Iowa, no contest. The crust is perfect and the toppings are generous. We order every Friday night.", source: 'Google' },
    { name: 'Jake T.', rating: 5, text: "Marco's has been my family's go-to for 15 years. Never disappoints. Fast delivery and always hot.", source: 'Google' },
    { name: 'Carla R.', rating: 5, text: "The Meat Lover's is unreal. Huge portions, great price. Mason City is lucky to have Marco's.", source: 'Facebook' },
  ],
  menuCategories: [
    { name: 'Pizzas', items: [
      { name: 'Classic Pepperoni', desc: 'House marinara, mozzarella, premium pepperoni', price: '$16.99' },
      { name: 'BBQ Chicken', desc: 'BBQ base, grilled chicken, red onions', price: '$18.99' },
      { name: 'Meat Lover\'s', desc: 'Pepperoni, sausage, ham, bacon, beef', price: '$21.99' },
      { name: 'Veggie Garden', desc: 'Pesto, roasted veggies, feta', price: '$15.99' },
      { name: 'Margherita', desc: 'Tomato, fresh mozzarella, basil', price: '$14.99' },
    ]},
    { name: 'Appetizers', items: [
      { name: 'Garlic Breadsticks', desc: 'Freshly baked with garlic butter', price: '$6.99' },
      { name: 'Mozzarella Sticks', desc: '8-piece, served with marinara', price: '$8.99' },
      { name: 'Wings', desc: '8-piece with your choice of sauce', price: '$11.99' },
    ]},
    { name: 'Salads', items: [
      { name: 'Caesar Salad', desc: 'Romaine, parmesan, house croutons', price: '$7.99' },
      { name: 'Garden Salad', desc: 'Mixed greens, veggies, Italian dressing', price: '$6.99' },
    ]},
    { name: 'Drinks & Desserts', items: [
      { name: 'Fountain Drinks', desc: 'Coke, Diet Coke, Sprite, Lemonade', price: '$2.99' },
      { name: '2-Liter Bottles', desc: 'Pepsi products', price: '$3.99' },
      { name: 'Cannoli', desc: 'Traditional Italian, house-made filling', price: '$4.99' },
    ]},
  ],
  socialVideos: [
    { type: 'reel', label: 'Watch us make fresh dough every morning', thumbnail: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'Family Night — the best deal in Mason City', thumbnail: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'The Meat Lover\'s being built layer by layer', thumbnail: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&auto=format&fit=crop' },
  ],
  seoKeywords: ['best pizza mason city ia', 'pizza delivery mason city iowa', 'pizza near me mason city', 'italian restaurant north iowa'],
  schemaType: 'PizzaRestaurant',
};

export const MEXICAN_CONFIG = {
  id: 'mexican',
  name: "Casa Fuego",
  tagline: "Authentic Mexican. Local Roots.",
  headline: "Real Mexican Food. Easier to Find. Easier to Choose.",
  subheadline: "From street tacos to family fajitas — Casa Fuego is built to show up when people search for Mexican food near Clear Lake.",
  cuisine: 'Mexican',
  city: 'Clear Lake',
  state: 'IA',
  phone: '(641) 555-0247',
  address: '318 Main Ave N, Clear Lake, IA 50428',
  hours: 'Mon–Thu 11am–9pm · Fri–Sat 11am–10pm · Sun 12pm–8pm',
  orderUrl: '#order',
  menuUrl: '#menu',
  directionsUrl: 'https://maps.google.com',
  primaryColor: '#16a34a',
  accentColor: '#ca8a04',
  heroImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1400&auto=format&fit=crop',
  logo: '🌮',
  rating: 4.9,
  reviewCount: 228,
  description: "Casa Fuego brings the bold, authentic flavors of Mexico to the heart of North Iowa. Family recipes, fresh ingredients, and a warm atmosphere that keeps locals coming back.",
  ownerName: "Miguel & Rosa Fuentes",
  ownerStory: "We brought our grandmother's recipes from Jalisco and made them home in Clear Lake. Every dish is made with love, fresh ingredients, and decades of tradition.",
  ownerImage: 'https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=400&auto=format&fit=crop',
  featuredDishes: [
    { name: 'Street Tacos (3)', price: '$12.99', desc: 'Carne asada or al pastor on handmade corn tortillas, onion, cilantro, salsa verde', image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop', badge: 'Most Popular' },
    { name: 'Sizzling Fajitas', price: '$17.99', desc: 'Grilled chicken or steak, peppers, onions, served with rice, beans, tortillas', image: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=600&auto=format&fit=crop', badge: 'Fan Fave' },
    { name: 'Loaded Nachos', price: '$13.99', desc: 'House chips, queso, jalapeños, guac, sour cream, choice of protein', image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&auto=format&fit=crop', badge: null },
    { name: 'Enchiladas Verdes', price: '$14.99', desc: 'Three cheese enchiladas, tomatillo salsa, crema, fresh herbs', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop', badge: 'Local Legend' },
  ],
  specials: [
    { day: 'Tuesday', title: 'Taco Tuesday', desc: '$2.50 street tacos all day. Dine-in only.', icon: '🌮' },
    { day: 'Thursday', title: 'Margarita Night', desc: 'Half-price house margaritas 5–8pm', icon: '🍹' },
    { day: 'Weekend', title: 'Family Feast', desc: 'Feed 4 for $49.99 — tacos, enchiladas, rice, beans', icon: '👨‍👩‍👧' },
    { day: 'Seasonal', title: 'Cinco de Mayo Fiesta', desc: 'Special menu, live music, outdoor seating', icon: '🎉' },
  ],
  reviews: [
    { name: 'Linda K.', rating: 5, text: "Authentic doesn't even cover it. These are the real deal. The al pastor tacos are the best I've had outside of Mexico.", source: 'Google' },
    { name: 'Brett W.', rating: 5, text: "Casa Fuego is our Friday tradition. The sizzling fajitas are insane, and the service is always warm and fast.", source: 'Google' },
    { name: 'Maria S.', rating: 5, text: "Finally, real Mexican food in North Iowa! The enchiladas verdes are incredible. This place is a gem.", source: 'Yelp' },
  ],
  menuCategories: [
    { name: 'Tacos', items: [
      { name: 'Street Tacos (3)', desc: 'Corn tortillas, carne asada or al pastor, onion, cilantro', price: '$12.99' },
      { name: 'Fish Tacos (2)', desc: 'Beer-battered cod, cabbage slaw, chipotle crema', price: '$11.99' },
      { name: 'Birria Tacos (3)', desc: 'Slow-braised beef, consommé dip, melted cheese', price: '$15.99' },
    ]},
    { name: 'Entrees', items: [
      { name: 'Chicken Fajitas', desc: 'Grilled chicken, peppers, onions, rice, beans, tortillas', price: '$17.99' },
      { name: 'Steak Fajitas', desc: 'Carne asada, peppers, onions, guac, tortillas', price: '$19.99' },
      { name: 'Enchiladas Verdes', desc: 'Three cheese enchiladas, tomatillo salsa', price: '$14.99' },
      { name: 'Chile Relleno', desc: 'Roasted poblano, cheese-stuffed, tomato sauce', price: '$13.99' },
    ]},
    { name: 'Starters', items: [
      { name: 'Guacamole & Chips', desc: 'Fresh-made daily, house chips', price: '$7.99' },
      { name: 'Loaded Nachos', desc: 'Queso, jalapeños, protein, guac', price: '$13.99' },
      { name: 'Elote (Street Corn)', desc: 'Grilled corn, cotija, chili, lime', price: '$5.99' },
    ]},
    { name: 'Drinks', items: [
      { name: 'House Margarita', desc: 'Lime, salt, tequila, triple sec — on the rocks or frozen', price: '$8.99' },
      { name: 'Agua Fresca', desc: 'Hibiscus, horchata, or tamarind', price: '$3.99' },
      { name: 'Mexican Coke', desc: 'Glass bottle, cane sugar', price: '$3.50' },
    ]},
  ],
  socialVideos: [
    { type: 'reel', label: 'Birria tacos dripping with consommé', thumbnail: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'Sizzling fajita plate hitting the table', thumbnail: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'Fresh guacamole made right at your table', thumbnail: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&auto=format&fit=crop' },
  ],
  seoKeywords: ['mexican restaurant clear lake iowa', 'best tacos north iowa', 'mexican food near me clear lake', 'authentic mexican clear lake ia'],
  schemaType: 'MexicanRestaurant',
};

export const BAR_CONFIG = {
  id: 'bar',
  name: "The Iron Rail Bar & Grill",
  tagline: "Cold Drinks. Great Food. Always Open.",
  headline: "Your Game Day Headquarters. Built to Be Found.",
  subheadline: "Sports bar, burgers, wings, and ice-cold drinks — The Iron Rail shows up when people search for bars and grills near Garner.",
  cuisine: 'Bar & Grill',
  city: 'Garner',
  state: 'IA',
  phone: '(641) 555-0318',
  address: '88 State St, Garner, IA 50438',
  hours: 'Mon–Thu 11am–11pm · Fri–Sat 11am–1am · Sun 12pm–10pm',
  orderUrl: '#order',
  menuUrl: '#menu',
  directionsUrl: 'https://maps.google.com',
  primaryColor: '#92400e',
  accentColor: '#d97706',
  heroImage: 'https://images.unsplash.com/photo-1554136575-791d2b8e8a4e?w=1400&auto=format&fit=crop',
  logo: '🍺',
  rating: 4.7,
  reviewCount: 189,
  description: "The Iron Rail is Garner's favorite sports bar — where locals come for ice-cold drinks, hand-pressed burgers, and every game on big screen. Locals since 2004.",
  ownerName: "Dave & Tammy Hartley",
  ownerStory: "We built this place for working folks who want a cold beer, a great burger, and a place to catch the game. Nothing fancy. Just the best bar food in Hancock County.",
  ownerImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&auto=format&fit=crop',
  featuredDishes: [
    { name: 'The Iron Rail Burger', price: '$13.99', desc: '1/2 lb hand-pressed beef, bacon, cheddar, house sauce, brioche bun', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop', badge: 'Local Legend' },
    { name: 'Game Day Wings (12)', price: '$14.99', desc: 'Choose your sauce: Buffalo, BBQ, Garlic Parmesan, or Honey Sriracha', image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600&auto=format&fit=crop', badge: 'Most Popular' },
    { name: 'Loaded Fries', price: '$9.99', desc: 'Seasoned fries, cheese sauce, bacon, jalapeños, ranch drizzle', image: 'https://images.unsplash.com/photo-1573080496219-bb964701c98d?w=600&auto=format&fit=crop', badge: null },
    { name: 'Pulled Pork Sandwich', price: '$12.99', desc: '12-hour smoked pork, coleslaw, pickles, BBQ sauce', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop', badge: 'Fan Fave' },
  ],
  specials: [
    { day: 'Monday', title: 'Monday Night Football Special', desc: 'Half-price wings during the game + $3 domestics', icon: '🏈' },
    { day: 'Wednesday', title: 'Burger & Beer Wednesday', desc: 'Any burger + domestic for $14.99', icon: '🍔' },
    { day: 'Friday', title: 'Happy Hour', desc: '$1 off all drinks, 4–6pm Friday', icon: '🍺' },
    { day: 'Weekend', title: 'Weekend Brunch + Bloody Marys', desc: 'Saturday & Sunday 11am–2pm', icon: '🥂' },
  ],
  reviews: [
    { name: 'Tom H.', rating: 5, text: "Best bar food in the county. The Iron Rail burger is worth every penny. Great atmosphere for game day.", source: 'Google' },
    { name: 'Amy J.', rating: 5, text: "Friendly staff, quick service, and the wings are phenomenal. This is our go-to for every big game.", source: 'Google' },
    { name: 'Chris D.', rating: 4, text: "Great local bar. Prices are fair, portions are huge. The pulled pork sandwich is my absolute favorite.", source: 'Facebook' },
  ],
  menuCategories: [
    { name: 'Burgers', items: [
      { name: 'Iron Rail Burger', desc: '1/2 lb beef, bacon, cheddar, house sauce', price: '$13.99' },
      { name: 'BBQ Bacon Burger', desc: 'Smoked BBQ, crispy bacon, onion rings on top', price: '$14.99' },
      { name: 'Mushroom Swiss', desc: 'Sautéed mushrooms, Swiss cheese, garlic aioli', price: '$13.99' },
      { name: 'Turkey Burger', desc: 'Ground turkey, avocado, tomato, spinach', price: '$12.99' },
    ]},
    { name: 'Wings & Apps', items: [
      { name: 'Wings (6)', desc: 'Buffalo, BBQ, Garlic Parm, or Honey Sriracha', price: '$8.99' },
      { name: 'Wings (12)', desc: 'Same great flavors, bigger order', price: '$14.99' },
      { name: 'Mozzarella Sticks', desc: '6-piece, marinara dipping sauce', price: '$7.99' },
      { name: 'Loaded Fries', desc: 'Cheese, bacon, jalapeño, ranch', price: '$9.99' },
    ]},
    { name: 'Sandwiches', items: [
      { name: 'Pulled Pork', desc: '12-hour smoked, coleslaw, pickles', price: '$12.99' },
      { name: 'Chicken Club', desc: 'Grilled or crispy, bacon, lettuce, tomato', price: '$11.99' },
      { name: 'Philly Cheesesteak', desc: 'Shaved beef, peppers, onions, provolone', price: '$13.99' },
    ]},
    { name: 'Drinks', items: [
      { name: 'Domestic Beer', desc: 'Bud Light, Coors Light, Miller Lite', price: '$4.00' },
      { name: 'Craft Beer', desc: 'Rotating local and regional taps', price: '$5.50' },
      { name: 'Cocktails', desc: 'Ask your bartender for today\'s specials', price: '$7.00+' },
      { name: 'Bloody Mary', desc: 'House mix, garnished right', price: '$8.00' },
    ]},
  ],
  socialVideos: [
    { type: 'reel', label: 'The Iron Rail Burger built from scratch', thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'Game Day at The Iron Rail — packed house!', thumbnail: 'https://images.unsplash.com/photo-1554136575-791d2b8e8a4e?w=400&auto=format&fit=crop' },
    { type: 'reel', label: 'Wing Wednesday — best wings in Garner', thumbnail: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&auto=format&fit=crop' },
  ],
  seoKeywords: ['sports bar garner iowa', 'bar and grill near me garner ia', 'best burgers hancock county iowa', 'wings garner iowa'],
  schemaType: 'BarOrPub',
};