import { Link } from 'react-router-dom';
import { ArrowRight, Compass, Eye, MessageSquareReply, Search, Workflow } from 'lucide-react';
import MarketingNav from '@/components/nav/MarketingNav';
import SiteFooter from '@/components/marketing/SiteFooter';
import SEOHead from '@/components/shared/SEOHead';
const stages=[
 {icon:Search,title:'Be understandable',text:'Make it clear what you do, who you help and which questions you can answer.'},
 {icon:Eye,title:'Be findable',text:'Website, search, Google, reviews, social and other channels can help the right people discover you.'},
 {icon:MessageSquareReply,title:'Respond well',text:'A lead is not useful if calls, forms, messages or after-hours inquiries disappear or wait too long.'},
 {icon:Workflow,title:'Follow through',text:'Simple follow-up and a clear handoff help turn interest into a real conversation without making the process impersonal.'},
];
export default function LocalLeadSystems(){return <div className="min-h-screen bg-slate-950 text-slate-200">
<SEOHead title="How Can My Business Get and Follow Up With More Leads? | NTA" description="Understand local lead generation as a connected system of visibility, response, follow-up and learning inside a Digital Growth Roadmap."/><MarketingNav/><main>
<section className="relative overflow-hidden border-b border-slate-800"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(245,158,11,0.17),_transparent_42%)]"/><div className="relative mx-auto max-w-6xl px-6 py-20 md:py-28"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-4 py-1.5 text-sm font-semibold text-amber-300"><Workflow className="h-4 w-4"/> Leads, response & follow-up</div><h1 className="max-w-4xl text-4xl font-black leading-tight text-white sm:text-5xl md:text-6xl">“We need more leads.” <span className="text-amber-400">First, let’s see what happens before and after someone raises their hand.</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-slate-300 md:text-xl">More traffic is not always the first answer. A business can lose opportunity because people cannot find it, do not understand it, cannot reach anyone, or never receive useful follow-up. A lead system connects those moments.</p><Link to="/start" className="mt-9 inline-flex items-center gap-2 rounded-xl bg-amber-600 px-7 py-4 font-bold text-white hover:bg-amber-500">Start a Free Growth Conversation <ArrowRight className="h-5 w-5"/></Link></div></section>
<section className="bg-white py-20 text-slate-900"><div className="mx-auto max-w-6xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-700">Follow the customer journey</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Find the gap before buying another tactic.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{stages.map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><Icon className="h-7 w-7 text-amber-600"/><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div>)}</div></div></section>
<section className="border-y border-slate-800 bg-slate-900 py-20"><div className="mx-auto max-w-5xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-400">NTA Point of View</p><h2 className="mt-3 text-3xl font-black text-white md:text-4xl">A lead system is not a bundle of marketing products.</h2><p className="mt-5 text-lg leading-relaxed text-slate-300">It is the connected experience from a person having a need to finding the business, understanding it, making contact, receiving a response and getting the next appropriate step. The Digital Growth Roadmap™ helps identify where that experience is breaking down.</p></div></section>
<section className="bg-white py-20 text-slate-900"><div className="mx-auto max-w-5xl px-6"><Compass className="h-8 w-8 text-amber-600"/><h2 className="mt-4 text-3xl font-black">The solution depends on the gap.</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">The next step might involve the website, Google, a campaign, reviews, phone handling, forms, text or email follow-up, internal workflow—or simply clearer information. NTA starts with the business before recommending the tool.</p></div></section>
<section className="bg-amber-950/30 py-20 text-center"><div className="mx-auto max-w-4xl px-6"><h2 className="text-3xl font-black text-white md:text-4xl">Start with the leads you already get—and the ones you may be losing.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">We can trace the path, find the gaps and decide what belongs on the Roadmap.</p><Link to="/start" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-600 px-8 py-4 font-bold text-white hover:bg-amber-500">Start a Free Growth Conversation <ArrowRight className="h-5 w-5"/></Link></div></section>
</main><SiteFooter/></div>}
