import React, { useState } from 'react';
import { createPageUrl } from '@/utils';
import { base44 } from '@/api/base44Client';
import MarketingNav from '@/components/nav/MarketingNav';
import SiteFooter from '@/components/marketing/SiteFooter';
import PillarHero from '@/components/templates/PillarHero';
import InternalLinks from '@/components/templates/InternalLinks';
import PillarCTA from '@/components/templates/PillarCTA';
import { BrainCircuit, Copy, RefreshCw, CheckCircle } from 'lucide-react';

const BUDGETS = ['Under $500/mo', '$500–$1,000/mo', '$1,000–$2,500/mo', '$2,500+/mo'];
const GOALS = ['More leads & calls', 'Brand awareness', 'Seasonal promotions', 'Launch a new service', 'Beat local competitors'];

const RELATED = [
  { label: 'System', title: 'The NTA Growth System', desc: 'How all channels work together', href: createPageUrl('GrowthSystem') },
  { label: 'Tool', title: 'TV Commercial Script Generator', desc: 'Generate a streaming TV ad script', href: createPageUrl('TvCommercialScriptGenerator') },
  { label: 'Platform', title: 'AI Marketing Platform', desc: 'Execute your plan with AI tools', href: createPageUrl('AiMarketingPlatform') },
];

export default function MarketingPlanGenerator() {
  const [form, setForm] = useState({ businessName: '', industry: '', city: '', goal: 'More leads & calls', budget: '$500–$1,000/mo', channels: [], notes: '' });
  const [plan, setPlan] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const CHANNELS = ['Social Media', 'Streaming TV', 'Google Ads', 'Email Marketing', 'Local SEO', 'Video Content'];

  const toggleChannel = (c) => {
    setForm(f => ({ ...f, channels: f.channels.includes(c) ? f.channels.filter(x => x !== c) : [...f.channels, c] }));
  };

  const handleGenerate = async () => {
    if (!form.businessName || !form.industry || !form.city) return;
    setLoading(true);
    setPlan('');
    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `Create a practical 90-day marketing plan for a local small business.

Business name: ${form.businessName}
Industry: ${form.industry}
City / Service area: ${form.city}
Primary goal: ${form.goal}
Monthly marketing budget: ${form.budget}
Preferred channels: ${form.channels.length ? form.channels.join(', ') : 'Open to all channels'}
Additional context: ${form.notes || 'None provided'}

Format the plan with these sections:
1. SITUATION SUMMARY — a brief honest assessment of this type of business's marketing position
2. PRIMARY STRATEGY — the one core approach that will drive the most results given the goal and budget
3. CHANNEL BREAKDOWN — for each relevant channel, what to do and how much budget to allocate
4. 90-DAY CALENDAR — what to do in Month 1, Month 2, and Month 3
5. QUICK WINS — 3 things to do in the first 7 days
6. SUCCESS METRICS — how to know if the plan is working

Be specific, practical, and oriented toward a local service business owner who is not a marketing expert.`,
    });
    setPlan(result);
    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(plan);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const ready = form.businessName && form.industry && form.city;

  return (
    <div className="bg-slate-950 min-h-screen">
      <MarketingNav />

      <PillarHero
        badge="Free Tool"
        heading="Marketing Plan Generator"
        subheading="Get a custom 90-day marketing plan built specifically for your business, industry, and goals — generated by AI in under 60 seconds."
        primaryCta="Generate My Plan Below"
        primaryHref="#generator"
      />

      {/* Tool */}
      <section id="generator" className="py-16 px-4 bg-slate-900 border-t border-slate-800">
        <div className="max-w-3xl mx-auto">
          <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-violet-500/10 rounded-xl flex items-center justify-center">
                <BrainCircuit className="w-5 h-5 text-violet-400" />
              </div>
              <div>
                <h2 className="text-white font-bold text-lg">Marketing Plan Generator</h2>
                <p className="text-slate-500 text-xs">Fill in your business details — get your 90-day plan instantly</p>
              </div>
            </div>

            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Business Name *</label>
                  <input
                    type="text"
                    placeholder="e.g. Smith's Plumbing"
                    value={form.businessName}
                    onChange={e => setForm(f => ({ ...f, businessName: e.target.value }))}
                    className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-white text-sm placeholder-slate-600 focus:outline-none focus:border-violet-500"
                  />
                </div>
                <div>
                  <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Industry *</label>
                  <input
                    type="text"
                    placeholder="e.g. Plumbing, HVAC, Restaurant"
                    value={form.industry}
                    onChange={e => setForm(f => ({ ...f, industry: e.target.value }))}
                    className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-white text-sm placeholder-slate-600 focus:outline-none focus:border-violet-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">City / Service Area *</label>
                <input
                  type="text"
                  placeholder="e.g. Chicago, IL"
                  value={form.city}
                  onChange={e => setForm(f => ({ ...f, city: e.target.value }))}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-white text-sm placeholder-slate-600 focus:outline-none focus:border-violet-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Primary Goal</label>
                <div className="flex flex-wrap gap-2">
                  {GOALS.map(g => (
                    <button key={g} onClick={() => setForm(f => ({ ...f, goal: g }))}
                      className={`text-xs font-semibold px-3 py-1.5 rounded-lg border transition-all ${form.goal === g ? 'bg-violet-600 border-violet-500 text-white' : 'bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-600'}`}>
                      {g}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Monthly Budget</label>
                <div className="flex flex-wrap gap-2">
                  {BUDGETS.map(b => (
                    <button key={b} onClick={() => setForm(f => ({ ...f, budget: b }))}
                      className={`text-xs font-semibold px-3 py-1.5 rounded-lg border transition-all ${form.budget === b ? 'bg-violet-600 border-violet-500 text-white' : 'bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-600'}`}>
                      {b}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Channels You're Interested In (optional)</label>
                <div className="flex flex-wrap gap-2">
                  {CHANNELS.map(c => (
                    <button key={c} onClick={() => toggleChannel(c)}
                      className={`text-xs font-semibold px-3 py-1.5 rounded-lg border transition-all ${form.channels.includes(c) ? 'bg-cyan-700 border-cyan-600 text-white' : 'bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-600'}`}>
                      {c}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-slate-400 text-xs font-semibold uppercase tracking-wide mb-1.5">Anything else we should know? (optional)</label>
                <textarea
                  rows={2}
                  placeholder="e.g. We just launched a new service, we're competing against a major chain, we have no social presence yet..."
                  value={form.notes}
                  onChange={e => setForm(f => ({ ...f, notes: e.target.value }))}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-white text-sm placeholder-slate-600 focus:outline-none focus:border-violet-500 resize-none"
                />
              </div>

              <button
                onClick={handleGenerate}
                disabled={!ready || loading}
                className="w-full bg-violet-600 hover:bg-violet-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold py-3.5 rounded-xl transition-all flex items-center justify-center gap-2"
              >
                {loading ? <><RefreshCw className="w-4 h-4 animate-spin" /> Building your marketing plan...</> : <><BrainCircuit className="w-4 h-4" /> Generate My 90-Day Plan</>}
              </button>
            </div>

            {/* Output */}
            {plan && (
              <div className="mt-6 border-t border-slate-800 pt-6">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-white font-bold text-sm">Your 90-Day Marketing Plan</h3>
                  <button onClick={handleCopy}
                    className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white border border-slate-700 hover:border-slate-500 px-3 py-1.5 rounded-lg transition-all">
                    {copied ? <><CheckCircle className="w-3.5 h-3.5 text-green-400" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy Plan</>}
                  </button>
                </div>
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
                  <pre className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap font-sans">{plan}</pre>
                </div>
                <div className="mt-5 bg-violet-950/40 border border-violet-800/30 rounded-xl p-5 text-center">
                  <p className="text-white font-bold text-sm mb-1">Want us to execute this plan for you?</p>
                  <p className="text-slate-400 text-xs mb-4">The NTA Growth System will implement every channel in this plan — automatically.</p>
                  <div className="flex flex-col sm:flex-row gap-2 justify-center">
                    <a href={createPageUrl('Get-Started')} className="bg-violet-600 hover:bg-violet-500 text-white font-bold text-sm px-5 py-2.5 rounded-xl transition-all">Start Free Trial</a>
                    <a href={createPageUrl('Book-Call')} className="border border-slate-700 hover:border-slate-500 text-slate-300 font-semibold text-sm px-5 py-2.5 rounded-xl transition-all">Book a Strategy Call</a>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>

      <InternalLinks heading="Related Resources" links={RELATED} />

      <PillarCTA
        heading="Let AI run your marketing — not just plan it."
        subheading="Start your free trial and put your plan into action today."
      />

      <SiteFooter />
    </div>
  );
}