import { Link } from 'react-router-dom';
import { ArrowRight, Compass, MonitorPlay, Target, Video } from 'lucide-react';
import MarketingNav from '@/components/nav/MarketingNav';
import SiteFooter from '@/components/marketing/SiteFooter';
import SEOHead from '@/components/shared/SEOHead';
export default function StreamingTvAdvertising(){return <div className="min-h-screen bg-slate-950 text-slate-200"><SEOHead title="Should My Business Use Streaming TV Advertising? | NTA" description="Understand where streaming TV and connected TV advertising may fit in a small business Digital Growth Roadmap."/><MarketingNav/><main>
<section className="relative overflow-hidden border-b border-slate-800"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(139,92,246,0.20),_transparent_42%)]"/><div className="relative mx-auto max-w-6xl px-6 py-20 md:py-28"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1.5 text-sm font-semibold text-violet-300"><MonitorPlay className="h-4 w-4"/> Streaming TV & connected TV</div><h1 className="max-w-4xl text-4xl font-black leading-tight text-white sm:text-5xl md:text-6xl">“Should my business be advertising on streaming TV?” <span className="text-violet-400">Maybe—if it fits the audience and the Roadmap.</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-slate-300 md:text-xl">Streaming TV can put a local or regional business in front of viewers watching internet-delivered television. But a channel is only useful when the message, audience, follow-up and larger business goal make sense together.</p><Link to="/start" className="mt-9 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-7 py-4 font-bold text-white hover:bg-violet-500">Start a Free Growth Conversation <ArrowRight className="h-5 w-5"/></Link></div></section>
<section className="bg-white py-20 text-slate-900"><div className="mx-auto max-w-6xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-violet-700">Questions before a campaign</p><h2 className="mt-3 text-3xl font-black md:text-4xl">What job would streaming TV do for the business?</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><Target className="h-7 w-7 text-violet-600"/><h3 className="mt-4 text-xl font-bold">Audience</h3><p className="mt-2 text-slate-600">Who are you trying to reach, where are they, and is video on connected television a sensible way to reach them?</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><Video className="h-7 w-7 text-violet-600"/><h3 className="mt-4 text-xl font-bold">Message</h3><p className="mt-2 text-slate-600">What useful, memorable idea should the viewer understand about the business in a short amount of time?</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><Compass className="h-7 w-7 text-violet-600"/><h3 className="mt-4 text-xl font-bold">Next step</h3><p className="mt-2 text-slate-600">What happens after someone sees the ad? The website, search presence, phone response and follow-up still matter.</p></div></div></div></section>
<section className="border-y border-slate-800 bg-slate-900 py-20"><div className="mx-auto max-w-5xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-violet-400">NTA Point of View</p><h2 className="mt-3 text-3xl font-black text-white md:text-4xl">Streaming TV is a possible channel—not a required package.</h2><p className="mt-5 text-lg leading-relaxed text-slate-300">NTA can help evaluate the role of video and streaming TV alongside the website, search, social communication, seasonal campaigns and customer follow-up. The Digital Growth Roadmap™ determines whether it belongs now, later, or not at all.</p></div></section>
<section className="bg-violet-950/30 py-20 text-center"><div className="mx-auto max-w-4xl px-6"><h2 className="text-3xl font-black text-white md:text-4xl">Start with the audience and the business goal.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">If streaming TV makes sense, we can work out the message, production, targeting and follow-up as part of the larger plan.</p><Link to="/start" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-8 py-4 font-bold text-white hover:bg-violet-500">Start a Free Growth Conversation <ArrowRight className="h-5 w-5"/></Link></div></section>
</main><SiteFooter/></div>}
