import React, { useEffect } from 'react';
import { ChevronDown, CheckCircle2 } from 'lucide-react';
import MarketingNav from '@/components/nav/MarketingNav';
import SiteFooter from '@/components/marketing/SiteFooter';
import LCHeader from '@/components/learning-center/LCHeader';
import LCInsightBlock from '@/components/learning-center/LCInsightBlock';
import LCRelatedVideos from '@/components/learning-center/LCRelatedVideos';
import LCCallToAction from '@/components/learning-center/LCCallToAction';
import { TrackProgress, TrackBottomNav } from '@/components/learning-center/TrackNavigation';

import SEOHead from '@/components/shared/SEOHead';
export default function VideoStorytellingBuildsConfidence() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 font-sans text-slate-200">
      <SEOHead 
        title="Video Storytelling Builds Customer Confidence | New Tech Advertising"
        description="How video storytelling builds trust and confidence with local customers. AI-powered video marketing for small businesses."
      />
      <MarketingNav />
      
      <main className="pt-24 pb-20">
        <LCHeader 
          title="Video Storytelling Builds Confidence"
          category="Video & CTV Marketing"
          readingTime="8 min read"
          breadcrumbs={[
            { label: "Knowledge Library", path: '/learning-center' },
            { label: 'Video & CTV Marketing', path: '/learning-center/category/video-ctv-marketing' },
            { label: 'Video Storytelling Builds Confidence' }
          ]}
        />

        <div className="max-w-4xl mx-auto px-6 mt-12">
          <TrackProgress trackName="Show Me Real Results" currentStep={5} totalSteps={5} color="purple" />

          {/* Featured Video */}
          <div className="mb-14 relative w-full aspect-video rounded-2xl overflow-hidden shadow-2xl border border-slate-800 bg-slate-900">
            <iframe 
              src="https://www.youtube.com/embed/3_P36VrK9jc?rel=0" 
              className="absolute top-0 left-0 w-full h-full border-0"
              allow="autoplay; encrypted-media; fullscreen" 
              title="Video Storytelling Builds Confidence"
            />
          </div>

          <div className="prose prose-invert prose-lg max-w-none">
            <p className="text-xl text-slate-300 leading-relaxed mb-10">
              Customers today research your business long before they ever pick up the phone. In an era where anyone can generate a wall of text using AI, consumers are actively looking for human proof. Authentic video storytelling has become the ultimate shortcut to building customer confidence, strengthening digital trust, and standing out in a crowded market.
            </p>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Why Confidence Matters In Marketing</h2>
            <p>
              When a potential customer is searching for a local service—whether it's a new roof, legal advice, or a marketing agency—their primary emotion isn't excitement; it's hesitation. They are afraid of making the wrong decision, being overcharged, or hiring someone unreliable.
            </p>
            <p>
              Modern buying behavior is "trust-first." Customers want immediate reassurance. They want to know:
            </p>
            <ul className="space-y-3 mb-8 list-none pl-0">
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">↳</span> Are you real?</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">↳</span> Are you competent?</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">↳</span> Are you easy to work with?</li>
            </ul>
            <p>
              Confidence reduces hesitation. The business that makes the customer feel the most comfortable and familiar before the initial contact is almost always the business that wins the job.
            </p>

            <LCInsightBlock 
              type="business_insight"
              title="The Familiarity Advantage"
              content="People prefer to do business with people they feel they already know. Video bridges the gap between being a random website and being a familiar, trusted local expert."
            />

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Why Video Builds Trust Faster</h2>
            <p>
              Text can be faked, outsourced, or generated by AI in seconds. Video requires someone to actually show up. When you use video, you instantly:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">
              {[
                'Make your brand feel human',
                'Demonstrate your expertise in real-time',
                'Show your personality and tone',
                'Answer complex questions visually',
                'Reduce customer anxiety and uncertainty',
                'Prove you actively do the work you claim',
                'Build immediate familiarity',
                'Stand out from faceless competitors'
              ].map((item, i) => (
                <div key={i} className="flex items-center gap-3 bg-slate-900 border border-slate-800 p-4 rounded-lg">
                  <CheckCircle2 className="w-5 h-5 text-blue-500 flex-shrink-0" />
                  <span className="text-slate-300 font-medium">{item}</span>
                </div>
              ))}
            </div>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Authentic Video vs Traditional Commercials</h2>
            <p>
              A massive shift has happened in what consumers respond to. The highly polished, slick local TV commercial is actually losing effectiveness because it feels like a sales pitch. Today, authenticity wins.
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-10 not-prose">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-xl font-bold text-rose-400 mb-4">Old Style (Traditional)</h3>
                <ul className="space-y-2 text-sm text-slate-300">
                  <li>• Highly scripted and overly polished</li>
                  <li>• Generic voiceovers and stock footage</li>
                  <li>• Sales-heavy "Buy Now" messaging</li>
                  <li>• Feels like an interruption</li>
                </ul>
              </div>
              <div className="bg-slate-900 border border-emerald-900/50 rounded-xl p-6">
                <h3 className="text-xl font-bold text-emerald-400 mb-4">Modern Style (Authentic)</h3>
                <ul className="space-y-2 text-sm text-slate-300">
                  <li>• Educational and conversational</li>
                  <li>• Real founders and real employees</li>
                  <li>• Practical explanations of the process</li>
                  <li>• Feels like helpful advice</li>
                </ul>
              </div>
            </div>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">How Video Supports AI Visibility & SEO</h2>
            <p>
              Video isn't just about human psychology; it is a massive driver of technical visibility. Search engines and AI models use engagement metrics to determine if a website is valuable.
            </p>
            <ul className="space-y-3 mb-8 list-none pl-0">
              <li className="flex items-start gap-3"><span className="text-blue-500 mt-1">✓</span> <strong>Time on Page:</strong> Embedding a video on your website drastically increases how long a visitor stays. Search engines view high "dwell time" as a massive trust signal.</li>
              <li className="flex items-start gap-3"><span className="text-blue-500 mt-1">✓</span> <strong>AI Content Understanding:</strong> When you publish a video and include a text transcript, AI models can easily process your expertise and recommend you in AI summaries.</li>
              <li className="flex items-start gap-3"><span className="text-blue-500 mt-1">✓</span> <strong>Social Sharing:</strong> Video is shared vastly more often than text, creating natural backlinks and social signals that boost your authority.</li>
            </ul>

            <LCInsightBlock 
              type="ai_impact"
              title="Video as a Verification Signal"
              content="AI systems scan the web to verify if a business is legitimate. Active YouTube channels with localized video content provide strong geographic and topical verification to AI models."
            />

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Types Of Videos Small Businesses Should Create</h2>
            <p>
              You don't need to be a Hollywood director to build trust. Start with videos that answer the questions your sales team fields every day:
            </p>
            <ul className="space-y-3 mb-8 list-none pl-0">
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">1.</span> <strong>The Welcome/Intro Video:</strong> A 60-second video on your homepage explaining who you are, who you serve, and why you care.</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">2.</span> <strong>FAQ Videos:</strong> Short videos answering common questions (e.g., "How much does a new roof cost?").</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">3.</span> <strong>Process Walkthroughs:</strong> Show customers exactly what happens after they hire you to remove the fear of the unknown.</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">4.</span> <strong>Customer Stories:</strong> Video testimonials from real customers explaining the problem they had and how you solved it.</li>
              <li className="flex items-start gap-3"><span className="text-emerald-500 mt-1">5.</span> <strong>Behind-the-Scenes:</strong> Show your team working. It proves you are active, busy, and capable.</li>
            </ul>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Why Consistency Matters More Than Perfection</h2>
            <p>
              Many business owners paralyze themselves by overthinking production quality. They wait months to film the "perfect" video. In modern marketing, helpful content filmed on an iPhone will drastically outperform a highly polished video that never gets published.
            </p>
            <p>
              Consistency builds familiarity. Repeated exposure to your face, your voice, and your expertise trains the local market to view you as the definitive authority in your space.
            </p>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Video, CTV & Modern Marketing Ecosystems</h2>
            <p>
              Video is the most versatile marketing asset you can create. Once you film a core educational video, it can power your entire omnichannel visibility system:
            </p>
            <p>
              It lives on <strong>YouTube</strong> to capture search traffic.<br/>
              It embeds on your <strong>Website</strong> to increase conversions.<br/>
              It gets sliced into shorts for <strong>Social Media</strong> (TikTok, Instagram).<br/>
              It runs as a premium ad on <strong>Connected TV (CTV)</strong> streaming services to build elite local brand awareness.
            </p>

            <h2 className="text-2xl font-bold text-white mt-12 mb-6">Real-World Business Comparison</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-10 not-prose">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-xl font-bold text-white mb-4">Business A: Text Only</h3>
                <p className="text-slate-400 mb-4 text-sm leading-relaxed">
                  Relies entirely on a generic website with stock photos and basic text descriptions of their services.
                </p>
                <ul className="space-y-2 text-sm text-slate-300">
                  <li>• High website bounce rate</li>
                  <li>• Low customer familiarity before calling</li>
                  <li>• Forces customers to read to understand value</li>
                  <li>• Blends in with every competitor</li>
                </ul>
              </div>
              <div className="bg-slate-900 border border-emerald-900/50 rounded-xl p-6">
                <h3 className="text-xl font-bold text-white mb-4">Business B: Video Driven</h3>
                <p className="text-slate-400 mb-4 text-sm leading-relaxed">
                  Features a founder introduction on the homepage, FAQ videos on service pages, and runs CTV ads locally.
                </p>
                <ul className="space-y-2 text-sm text-slate-300">
                  <li>• High engagement and time on site</li>
                  <li>• Prospects call already feeling comfortable</li>
                  <li>• Educates customers effortlessly</li>
                  <li>• Stands out as the clear market authority</li>
                </ul>
              </div>
            </div>

            <h2 className="text-2xl font-bold text-white mt-16 mb-8">Frequently Asked Questions</h2>
            <div className="space-y-4 mb-16 not-prose">
              {[
                { q: "Do small businesses really need video?", a: "Yes. Customers now expect it. If your competitor has videos explaining their process and you only have text, the customer will inherently trust your competitor more." },
                { q: "Does video improve SEO?", a: "Absolutely. Video increases dwell time on your website, which is a massive ranking factor for Google. It also allows you to capture search traffic directly from YouTube, the world's second-largest search engine." },
                { q: "What types of videos build the most trust?", a: "Authentic, unscripted educational videos build the most trust. Answering common customer questions directly and transparently proves your expertise far better than a promotional commercial." },
                { q: "Do videos need to look professional?", a: "They need to look and sound clear, but they do not need to look like a Hollywood movie. Good lighting (like sitting near a window) and clear audio (a cheap lapel mic) are enough to produce highly effective content." },
                { q: "Can AI help create videos?", a: "Yes. While authentic human video is best for trust, AI tools (like HeyGen or script generators) can help you rapidly produce educational content, scale your output, or draft scripts to make filming easier." },
              ].map((faq, i) => (
                <details key={i} className="group bg-slate-900 border border-slate-800 rounded-xl">
                  <summary className="flex justify-between items-center font-bold cursor-pointer list-none p-5 text-white">
                    <span>{faq.q}</span>
                    <span className="transition group-open:rotate-180">
                      <ChevronDown className="w-5 h-5 text-slate-500" />
                    </span>
                  </summary>
                  <div className="text-slate-400 p-5 pt-0 leading-relaxed border-t border-slate-800 mt-2">
                    {faq.a}
                  </div>
                </details>
              ))}
            </div>

            <div className="not-prose">
              <LCCallToAction 
                mode="audit" 
                title="Is Your Website Building Confidence?" 
                description="Get a free AI visibility audit to see how your digital presence and video strategy stack up against your top local competitors." 
              />
            </div>

            <TrackBottomNav 
              prevLink="/i-was-early-again"
              prevText="← Previous: Founder's Story"
              nextLink="https://calendar.app.google/p6ieYanvwhixXxZ67"
              nextText="🎉 Track Complete! Book a Free Call →"
              color="purple"
            />
          </div>

          <div className="mt-20 pt-12 border-t border-slate-800">
            <LCRelatedVideos currentVideoId="video-storytelling-builds-confidence" limit={3} category="Video & CTV Marketing" />
          </div>
        </div>
      </main>
      
      <SiteFooter />
    </div>
  );
}