export const LEARNING_CATEGORIES = [
  { id: 'ai-visibility-search', title: 'AI Visibility & Search', description: 'Master zero-click searches, AI overviews, and structured data.' },
  { id: 'digital-trust-reputation', title: 'Digital Trust & Reputation', description: 'Build a verifiable digital footprint that AI models trust.' },
  { id: 'modern-marketing-systems', title: 'Modern Marketing Systems', description: 'Stop buying random tactics and start building growth engines.' },
  { id: 'video-ctv-marketing', title: 'Video & CTV Marketing', description: 'Leverage authentic video and connected TV to drive local leads.' },
  { id: 'ai-basics-small-businesses', title: 'AI Basics For Small Businesses', description: 'Practical AI applications to save time and punch above your weight.' }
];

export const VIDEO_CATEGORIES = [
  'All', 'AI Visibility & Search', 'Digital Trust & Reputation', 'Modern Marketing Systems', 'Video & CTV Marketing', 'AI Basics For Small Businesses'
];

export const LEARNING_CONTENT = [
  {
    id: 'what-changed-online',
    title: 'What Changed Online',
    slug: 'what-changed-online',
    category: 'AI Visibility & Search',
    categoryId: 'ai-visibility-search',
    shortDescription: 'Understand zero-click searches, AI overviews, and what to do next.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI Visibility', 'Zero-Click', 'Search'],
    tags: ['AI Visibility', 'Zero-Click', 'Search'],
    status: 'published'
  },
  {
    id: 'ai-visibility-basics',
    title: 'AI Visibility Basics',
    slug: 'ai-visibility-basics',
    category: 'AI Visibility & Search',
    categoryId: 'ai-visibility-search',
    shortDescription: 'How ChatGPT and Gemini choose which local businesses to recommend.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI Basics', 'ChatGPT', 'Gemini'],
    tags: ['AI Basics', 'ChatGPT', 'Gemini'],
    status: 'published'
  },
  {
    id: 'seo-vs-ai-search',
    title: 'SEO vs AI Search',
    slug: 'seo-vs-ai-search',
    category: 'AI Visibility & Search',
    categoryId: 'ai-visibility-search',
    shortDescription: 'Why traditional SEO is dying and how AI Search Optimization replaces it.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['SEO', 'AI Search', 'Optimization'],
    tags: ['SEO', 'AI Search', 'Optimization'],
    status: 'published'
  },
  {
    id: 'practical-ai-for-small-businesses',
    title: 'Practical AI For Small Businesses',
    slug: 'practical-ai-for-small-businesses',
    category: 'AI Basics For Small Businesses',
    categoryId: 'ai-basics-small-businesses',
    shortDescription: 'Real tools you can use today to save time and generate more leads.',
    articleContent: '',
    youtubeId: 'scPcJSMFn-E',
    youtubeUrl: 'https://youtu.be/scPcJSMFn-E',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI For Small Business', 'Local Marketing'],
    tags: ['AI For Small Business', 'Local Marketing'],
    status: 'published'
  },
  {
    id: 'growth-systems-vs-campaigns',
    title: 'Growth Systems vs Campaigns',
    slug: 'growth-systems-vs-campaigns',
    category: 'Modern Marketing Systems',
    categoryId: 'modern-marketing-systems',
    shortDescription: 'How a true growth system scales predictably, while campaigns burn through cash.',
    articleContent: '',
    youtubeId: '6kB55gnGGHo',
    youtubeUrl: 'https://youtu.be/6kB55gnGGHo',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Growth Systems', 'Marketing Systems'],
    tags: ['Growth Systems', 'Marketing Systems'],
    status: 'published'
  },
  {
    id: 'reputation-is-now-a-growth-engine',
    title: 'Reputation Is Now a Growth Engine',
    slug: 'reputation-is-now-a-growth-engine',
    category: 'Digital Trust & Reputation',
    categoryId: 'digital-trust-reputation',
    shortDescription: 'Turn your customer reviews into your most powerful local SEO asset.',
    articleContent: '',
    youtubeId: 'BT3WY2WdVDY',
    youtubeUrl: 'https://youtu.be/BT3WY2WdVDY',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Reputation Marketing', 'Reviews', 'Digital Trust'],
    tags: ['Reputation Marketing', 'Reviews', 'Digital Trust'],
    status: 'published'
  },
  {
    id: 'hidden-cost-of-outdated-marketing',
    title: 'The Hidden Cost of Outdated Marketing',
    slug: 'hidden-cost-of-outdated-marketing',
    category: 'Modern Marketing Systems',
    categoryId: 'modern-marketing-systems',
    shortDescription: 'How holding onto legacy SEO and traditional websites is slowly bleeding your business dry.',
    articleContent: '',
    youtubeId: 'jU_2Wae-_14',
    youtubeUrl: 'https://youtu.be/jU_2Wae-_14',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Modern Marketing', 'SEO', 'Business Growth'],
    tags: ['Modern Marketing', 'SEO', 'Business Growth'],
    status: 'published'
  },
  {
    id: 'role-of-ai-in-local-marketing',
    title: 'The Role of AI in Local Marketing',
    slug: 'role-of-ai-in-local-marketing',
    category: 'AI Basics For Small Businesses',
    categoryId: 'ai-basics-small-businesses',
    shortDescription: 'A no-BS guide to how small businesses are actually using AI to generate more revenue.',
    articleContent: '',
    youtubeId: 'scPcJSMFn-E', 
    youtubeUrl: 'https://youtu.be/scPcJSMFn-E',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI Visibility', 'Local Marketing'],
    tags: ['AI Visibility', 'Local Marketing'],
    status: 'published'
  },
  {
    id: 'web-accessibility-trust',
    title: 'Web Accessibility: The Foundation of Digital Trust',
    slug: 'web-accessibility-trust',
    category: 'Digital Trust & Reputation',
    categoryId: 'digital-trust-reputation',
    shortDescription: 'Why accessible websites rank better in AI search and build instant credibility.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Accessibility', 'Digital Trust'],
    tags: ['Accessibility', 'Digital Trust'],
    status: 'published'
  },
  {
    id: 'building-digital-trust',
    title: 'Building Digital Trust',
    slug: 'building-digital-trust',
    category: 'Digital Trust & Reputation',
    categoryId: 'digital-trust-reputation',
    shortDescription: 'How to proactively build a digital reputation that search engines and AI models trust implicitly.',
    articleContent: '',
    youtubeId: 'E5vE1kXlAhw',
    youtubeUrl: 'https://youtu.be/E5vE1kXlAhw',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Digital Trust', 'Customer Confidence'],
    tags: ['Digital Trust', 'Customer Confidence'],
    status: 'published'
  },
  {
    id: 'video-storytelling-builds-confidence',
    title: 'Video Storytelling Builds Confidence',
    slug: 'video-storytelling-builds-confidence',
    category: 'Video & CTV Marketing',
    categoryId: 'video-ctv-marketing',
    shortDescription: 'Stop selling and start showing. How authentic video creates instant customer confidence.',
    articleContent: '',
    youtubeId: '3_P36VrK9jc',
    youtubeUrl: 'https://youtu.be/3_P36VrK9jc',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Video Marketing', 'Digital Trust'],
    tags: ['Video Marketing', 'Digital Trust'],
    status: 'published'
  },
  {
    id: 'campaigns-vs-authority',
    title: 'Campaigns vs Authority',
    slug: 'campaigns-vs-authority',
    category: 'AI Visibility & Search',
    categoryId: 'ai-visibility-search',
    shortDescription: 'Stop running endless disconnected campaigns and start building compounding digital authority.',
    articleContent: '',
    youtubeId: '6Toyby7CTsA',
    youtubeUrl: 'https://youtu.be/6Toyby7CTsA',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Authority Marketing', 'AI Visibility'],
    tags: ['Authority Marketing', 'AI Visibility'],
    status: 'published'
  },
  {
    id: 'the-future-belongs-to-market-leaders',
    title: 'The Future Belongs to Market Leaders',
    slug: 'the-future-belongs-to-market-leaders',
    category: 'AI Visibility & Search',
    categoryId: 'ai-visibility-search',
    shortDescription: 'Why AI search, customer behavior, trust signals, and digital authority favor businesses that become recognized local market leaders.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI Search', 'Digital Authority'],
    tags: ['AI Search', 'Digital Authority'],
    status: 'published'
  },
  {
    id: 'the-power-of-consistency',
    title: 'The Power of Consistency',
    slug: 'the-power-of-consistency',
    category: 'Digital Trust & Reputation',
    categoryId: 'digital-trust-reputation',
    shortDescription: 'Why consistent data across the web is the number one ranking signal for AI.',
    articleContent: '',
    youtubeUrl: null,
    youtubeId: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['Consistency', 'AI Ranking'],
    tags: ['Consistency', 'AI Ranking'],
    status: 'planned'
  },
  {
    id: 'websites-as-salespeople',
    title: 'Websites as Salespeople',
    slug: 'websites-as-salespeople',
    category: 'Modern Marketing Systems',
    categoryId: 'modern-marketing-systems',
    shortDescription: 'Modern websites act like salespeople by building trust, answering questions, and helping businesses get found in AI search.',
    articleContent: '',
    youtubeId: 'elcnGAfYdgk',
    youtubeUrl: 'https://youtu.be/elcnGAfYdgk',
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['websites as salespeople', 'AI search websites', 'small business websites', 'modern website strategy', 'AI visibility', 'digital trust', 'local business marketing', 'Midwest business marketing', 'website conversion strategy'],
    tags: ['modern website strategy', 'AI visibility', 'digital trust'],
    status: 'published'
  },
  {
    id: 'ai-brought-me-out-of-retirement',
    title: 'AI Brought Me Out of Retirement',
    slug: 'ai-brought-me-out-of-retirement',
    category: 'Modern Marketing Systems',
    categoryId: 'modern-marketing-systems',
    shortDescription: 'After 45 years in business, NTA founder Rick Hesse came out of retirement to launch the region\'s first AI-powered marketing agency.',
    articleContent: '',
    youtubeId: null,
    youtubeUrl: null,
    thumbnailImage: null,
    featuredImage: null,
    seoKeywords: ['AI Marketing', 'Local Business Growth', 'Marketing Systems'],
    tags: ['AI Marketing', 'Local Business Growth', 'Marketing Systems'],
    status: 'published'
  }
];

export const LEARNING_ARTICLES = LEARNING_CONTENT.map(item => ({
  id: item.id,
  title: item.title,
  category: item.category,
  categoryId: item.categoryId,
  link: `/${item.slug}`,
  path: `/${item.slug}`,
  route: `/${item.slug}`,
  slug: item.slug,
  description: item.shortDescription,
  excerpt: item.shortDescription,
  status: item.status,
  priority: 'high',
  relatedArticleSlug: item.slug,
  relatedVideoId: item.id,
  relatedVideoIds: [item.id],
  youtubeUrl: item.youtubeUrl,
  thumbnailUrl: item.thumbnailImage,
  tag: item.tags?.[0] || item.category
}));

export const LEARNING_VIDEOS = LEARNING_CONTENT.map(item => ({
  id: item.id,
  title: item.title,
  slug: item.slug,
  category: item.category,
  duration: '', 
  youtubeId: item.youtubeId,
  thumbnail: item.thumbnailImage,
  description: item.shortDescription,
  status: item.youtubeId ? 'published' : 'planned',
  priority: 'high',
  relatedArticleSlug: item.slug,
  relatedVideoIds: [item.id],
  youtubeUrl: item.youtubeUrl,
  thumbnailUrl: item.thumbnailImage,
  tags: item.tags
}));