import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { base44 } from '@/api/base44Client';
import {
  Search, BookOpen, GraduationCap, Target, Palette, Globe,
  Settings, Heart, ChevronRight, ChevronDown, Link2, Plus,
  Check, X, Loader2, Sparkles, Eye, ArrowRight, Filter,
  Network, Lightbulb, FileText, MessageSquare, Video, Shield,
  Briefcase, Users, Zap, BarChart3, RefreshCw, Clock,
  AlertTriangle, CheckCircle2, XCircle, ExternalLink,
  Database, Layers, GitBranch, Star, TrendingUp, Coffee,
  Bot, Brain, Cpu, Workflow, BookMarked, Compass
} from 'lucide-react';
import RecommendationPanel from '@/components/RecommendationPanel';

// ─────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────

const KNOWLEDGE_DOMAINS = [
  { key: 'thought_leadership', label: 'Thought Leadership', icon: Lightbulb, color: 'text-amber-400', bg: 'bg-amber-500/10', border: 'border-amber-500/20', accent: 'amber' },
  { key: 'education_training', label: 'Education & Training', icon: GraduationCap, color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20', accent: 'emerald' },
  { key: 'sales_intelligence', label: 'Sales Intelligence', icon: Target, color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20', accent: 'blue' },
  { key: 'brand_creative', label: 'Brand & Creative', icon: Palette, color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/20', accent: 'purple' },
  { key: 'market_intelligence', label: 'Market Intelligence', icon: Globe, color: 'text-cyan-400', bg: 'bg-cyan-500/10', border: 'border-cyan-500/20', accent: 'cyan' },
  { key: 'operational_knowledge', label: 'Operational Knowledge', icon: Settings, color: 'text-slate-400', bg: 'bg-slate-500/10', border: 'border-slate-500/20', accent: 'slate' },
  { key: 'founder_wisdom', label: 'Founder Wisdom', icon: Heart, color: 'text-rose-400', bg: 'bg-rose-500/10', border: 'border-rose-500/20', accent: 'rose' },
];

const RELATIONSHIP_TYPES = [
  { key: 'supports', label: 'Supports', icon: '→', color: 'text-emerald-400' },
  { key: 'references', label: 'References', icon: '↗', color: 'text-blue-400' },
  { key: 'derived_from', label: 'Derived From', icon: '←', color: 'text-purple-400' },
  { key: 'feeds', label: 'Feeds', icon: '⇢', color: 'text-cyan-400' },
  { key: 'related_to', label: 'Related To', icon: '↔', color: 'text-slate-400' },
  { key: 'replaces', label: 'Replaces', icon: '⊘', color: 'text-amber-400' },
  { key: 'duplicate_of', label: 'Duplicate Of', icon: '⊜', color: 'text-red-400' },
  { key: 'uses', label: 'Uses', icon: '⊕', color: 'text-teal-400' },
  { key: 'required_by', label: 'Required By', icon: '⊗', color: 'text-orange-400' },
  { key: 'generated_by', label: 'Generated By', icon: '⊛', color: 'text-violet-400' },
  { key: 'consumed_by', label: 'Consumed By', icon: '⊙', color: 'text-lime-400' },
  { key: 'superseded_by', label: 'Superseded By', icon: '⊖', color: 'text-red-300' },
  { key: 'parent_of', label: 'Parent Of', icon: '↓', color: 'text-indigo-400' },
  { key: 'child_of', label: 'Child Of', icon: '↑', color: 'text-indigo-300' },
  { key: 'training_source', label: 'Training Source', icon: '📖', color: 'text-emerald-300' },
  { key: 'knowledge_source', label: 'Knowledge Source', icon: '🧠', color: 'text-amber-300' },
];

const ASSET_TYPE_META = {
  BlogPost: { icon: FileText, label: 'Blog Post', domain: 'thought_leadership' },
  KnowledgeArticle: { icon: BookOpen, label: 'Knowledge Article', domain: 'education_training' },
  KnowledgeCapture: { icon: Lightbulb, label: 'Knowledge Capture', domain: 'operational_knowledge' },
  CaseStudy: { icon: Briefcase, label: 'Case Study', domain: 'sales_intelligence' },
  GapAudit: { icon: Shield, label: 'AI Visibility Audit', domain: 'sales_intelligence' },
  DiscoveryCall: { icon: MessageSquare, label: 'Discovery Call', domain: 'sales_intelligence' },
  SalesKnowledgeBase: { icon: Target, label: 'Sales KB Entry', domain: 'sales_intelligence' },
  SalesAgentPrompts: { icon: Bot, label: 'Sales Agent Prompt', domain: 'sales_intelligence' },
  SOPWorkflow: { icon: Workflow, label: 'SOP Workflow', domain: 'operational_knowledge' },
  ChatbotKnowledge: { icon: MessageSquare, label: 'Chatbot Knowledge', domain: 'market_intelligence' },
  BrandDNA: { icon: Palette, label: 'Brand DNA', domain: 'brand_creative' },
  BrandProfile: { icon: Palette, label: 'Brand Profile', domain: 'brand_creative' },
  VideoTemplate: { icon: Video, label: 'Video Template', domain: 'brand_creative' },
  VideoScript: { icon: Video, label: 'Video Script', domain: 'brand_creative' },
  AIPromptTemplates: { icon: Cpu, label: 'AI Prompt Template', domain: 'brand_creative' },
  TopicCluster: { icon: Layers, label: 'Topic Cluster', domain: 'market_intelligence' },
  IndustryIntel: { icon: Globe, label: 'Industry Intel', domain: 'market_intelligence' },
  LocalMarketIntel: { icon: Compass, label: 'Local Market Intel', domain: 'market_intelligence' },
  AuthorityMap: { icon: Network, label: 'Authority Map', domain: 'market_intelligence' },
  AuthorityPlan: { icon: TrendingUp, label: 'Authority Plan', domain: 'market_intelligence' },
  ExecutiveBrief: { icon: Coffee, label: 'Executive Brief', domain: 'operational_knowledge' },
  KnowledgeGapSignal: { icon: AlertTriangle, label: 'Gap Signal', domain: 'operational_knowledge' },
  TrainingProgressProfile: { icon: GraduationCap, label: 'Training Profile', domain: 'education_training' },
  ContentTopics: { icon: BookMarked, label: 'Content Topic', domain: 'thought_leadership' },
  ProofAsset: { icon: Star, label: 'Proof Asset', domain: 'sales_intelligence' },
  HardcodedPage: { icon: FileText, label: 'Hardcoded Page', domain: 'thought_leadership' },
  DiscoveryTool: { icon: Compass, label: 'Discovery Tool', domain: 'sales_intelligence' },
  AIAgent: { icon: Brain, label: 'AI Agent', domain: 'operational_knowledge' },
  ExternalDocument: { icon: ExternalLink, label: 'External Doc', domain: 'operational_knowledge' },
};

// ─────────────────────────────────────────────────
// Static Knowledge Registry
// ─────────────────────────────────────────────────
// Hardcoded pages, discovery tools, and AI agents
// that aren't in the entity system but are knowledge assets.

const STATIC_ASSETS = [
  // Hardcoded Thought Leadership Articles
  { type: 'HardcodedPage', id: 'ai-brought-me-out-of-retirement', title: 'AI Brought Me Out Of Retirement', domain: 'founder_wisdom', tags: 'personal,ai,story' },
  { type: 'HardcodedPage', id: 'i-was-early-again', title: 'I Was Early Again', domain: 'founder_wisdom', tags: 'personal,ai,timing' },
  { type: 'HardcodedPage', id: 'the-future-belongs-to-market-leaders', title: 'The Future Belongs To Market Leaders', domain: 'thought_leadership', tags: 'vision,authority' },
  { type: 'HardcodedPage', id: 'the-hidden-cost-of-outdated-marketing', title: 'The Hidden Cost of Outdated Marketing', domain: 'thought_leadership', tags: 'pain,education' },
  { type: 'HardcodedPage', id: 'the-role-of-ai-in-local-marketing', title: 'The Role of AI in Local Marketing', domain: 'thought_leadership', tags: 'ai,local' },
  { type: 'HardcodedPage', id: 'what-changed-online', title: 'What Changed Online', domain: 'thought_leadership', tags: 'digital,landscape' },
  { type: 'HardcodedPage', id: 'reputation-is-now-a-growth-engine', title: 'Reputation Is Now A Growth Engine', domain: 'thought_leadership', tags: 'reputation,growth' },
  { type: 'HardcodedPage', id: 'building-digital-trust', title: 'Building Digital Trust', domain: 'thought_leadership', tags: 'trust,digital' },
  { type: 'HardcodedPage', id: 'video-storytelling-builds-confidence', title: 'Video Storytelling Builds Confidence', domain: 'thought_leadership', tags: 'video,storytelling' },
  { type: 'HardcodedPage', id: 'websites-as-salespeople', title: 'Websites As Salespeople', domain: 'thought_leadership', tags: 'website,sales' },
  { type: 'HardcodedPage', id: 'campaigns-vs-authority', title: 'Campaigns Vs Authority', domain: 'thought_leadership', tags: 'authority,philosophy' },
  { type: 'HardcodedPage', id: 'growth-systems-vs-campaigns', title: 'Growth Systems Vs Campaigns', domain: 'thought_leadership', tags: 'systems,growth' },
  { type: 'HardcodedPage', id: 'seo-vs-ai-search', title: 'SEO Vs AI Search', domain: 'thought_leadership', tags: 'seo,ai,search' },
  { type: 'HardcodedPage', id: 'digital-risks', title: 'Digital Risks', domain: 'thought_leadership', tags: 'risk,awareness' },
  { type: 'HardcodedPage', id: 'practical-ai-for-small-businesses', title: 'Practical AI For Small Businesses', domain: 'education_training', tags: 'ai,small-business,guide' },

  // Hardcoded Case Studies
  { type: 'HardcodedPage', id: 'case-study-johnson-heating', title: 'Johnson Heating Case Study', domain: 'sales_intelligence', tags: 'hvac,case-study,johnson' },
  { type: 'HardcodedPage', id: 'case-study-monson-plumbing', title: 'Monson Plumbing Case Study', domain: 'sales_intelligence', tags: 'plumbing,case-study,monson' },
  { type: 'HardcodedPage', id: 'case-study-papa-everetts', title: "Papa Everett's Case Study", domain: 'sales_intelligence', tags: 'restaurant,case-study,papa-everetts' },

  // Discovery Tools
  { type: 'DiscoveryTool', id: 'business-growth-conversation', title: 'Business Growth Conversation™', domain: 'sales_intelligence', tags: 'discovery,lead-gen' },
  { type: 'DiscoveryTool', id: 'community-growth-conversation', title: 'Community Growth Conversation™', domain: 'market_intelligence', tags: 'community,partnership' },
  { type: 'DiscoveryTool', id: 'ai-learning-conversation', title: 'AI Learning Conversation™', domain: 'education_training', tags: 'ai,learning,assessment' },
  { type: 'DiscoveryTool', id: 'growth-navigator', title: 'Growth Navigator™', domain: 'sales_intelligence', tags: 'growth,navigation' },
  { type: 'DiscoveryTool', id: 'nta-business-score', title: 'NTA Business Score™', domain: 'sales_intelligence', tags: 'score,assessment' },
  { type: 'DiscoveryTool', id: 'relationship-builder', title: 'Relationship Builder™', domain: 'market_intelligence', tags: 'community,relationships' },
  { type: 'DiscoveryTool', id: 'growth-roadmap', title: 'Growth Roadmap™', domain: 'sales_intelligence', tags: 'roadmap,planning' },
  { type: 'DiscoveryTool', id: 'growth-framework', title: 'Growth Framework™', domain: 'education_training', tags: 'framework,entry-point' },

  // AI Agents
  { type: 'AIAgent', id: 'content-multiplier', title: 'Content Multiplier Agent', domain: 'brand_creative', tags: 'ai,content,automation' },
  { type: 'AIAgent', id: 'growth-guide', title: 'Growth Guide Agent', domain: 'education_training', tags: 'ai,growth,guidance' },
  { type: 'AIAgent', id: 'video-agent', title: 'Video Production Agent', domain: 'brand_creative', tags: 'ai,video,production' },
  { type: 'AIAgent', id: 'performance-report-agent', title: 'Performance Report Agent', domain: 'operational_knowledge', tags: 'ai,reporting,performance' },

  // AI Agent Ownership
  { type: 'AIAgent', id: 'chatgpt', title: 'ChatGPT — Architecture, Executive, Strategy, K-Series', domain: 'operational_knowledge', tags: 'ai,architecture,strategy' },
  { type: 'AIAgent', id: 'viktor', title: 'Viktor — Execution, Automation, Operations, A-Series', domain: 'operational_knowledge', tags: 'ai,execution,automation' },
  { type: 'AIAgent', id: 'gemini', title: 'Gemini — Organization, Consistency, Review, Knowledge QA', domain: 'operational_knowledge', tags: 'ai,review,quality' },

  // Founder Wisdom content
  { type: 'HardcodedPage', id: 'my-journey-through-faith-and-failure', title: 'My Journey Through Faith and Failure', domain: 'founder_wisdom', tags: 'faith,failure,personal' },
  { type: 'HardcodedPage', id: 'talking-about-jesus', title: 'Talking About Jesus', domain: 'founder_wisdom', tags: 'faith,personal,values' },
  { type: 'HardcodedPage', id: 'the-questions-that-changed-me', title: 'The Questions That Changed Me', domain: 'founder_wisdom', tags: 'personal,growth,reflection' },
];

// ─────────────────────────────────────────────────
// Subcomponents
// ─────────────────────────────────────────────────

function ConfidenceBadge({ score }) {
  const color = score >= 80 ? 'text-emerald-400 bg-emerald-500/10' :
    score >= 60 ? 'text-blue-400 bg-blue-500/10' :
    score >= 40 ? 'text-amber-400 bg-amber-500/10' :
    'text-slate-400 bg-slate-500/10';
  return (
    <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${color}`}>
      {score}%
    </span>
  );
}

function StatusBadge({ status }) {
  const config = {
    suggested: { color: 'text-blue-400 bg-blue-500/10', label: 'Suggested' },
    pending_review: { color: 'text-amber-400 bg-amber-500/10', label: 'Pending' },
    approved: { color: 'text-emerald-400 bg-emerald-500/10', label: 'Approved' },
    rejected: { color: 'text-red-400 bg-red-500/10', label: 'Rejected' },
    archived: { color: 'text-slate-400 bg-slate-500/10', label: 'Archived' },
  };
  const c = config[status] || config.suggested;
  return <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${c.color}`}>{c.label}</span>;
}

function DomainBadge({ domainKey }) {
  const domain = KNOWLEDGE_DOMAINS.find(d => d.key === domainKey);
  if (!domain) return null;
  const Icon = domain.icon;
  return (
    <span className={`inline-flex items-center gap-1 text-[10px] font-mono px-1.5 py-0.5 rounded ${domain.bg} ${domain.color} border ${domain.border}`}>
      <Icon className="w-3 h-3" />
      {domain.label}
    </span>
  );
}

function AssetTypeIcon({ type, className = 'w-4 h-4' }) {
  const meta = ASSET_TYPE_META[type];
  if (!meta) return <Database className={className + ' text-slate-500'} />;
  const Icon = meta.icon;
  return <Icon className={className} />;
}

// ─────────────────────────────────────────────────
// Domain Sidebar Item
// ─────────────────────────────────────────────────

function DomainItem({ domain, assets, isExpanded, onToggle, onSelectAsset, selectedAssetId }) {
  const Icon = domain.icon;
  const domainAssets = assets.filter(a => a.domain === domain.key);
  const count = domainAssets.length;

  // Group by type
  const groups = {};
  domainAssets.forEach(a => {
    const label = ASSET_TYPE_META[a.type]?.label || a.type;
    if (!groups[label]) groups[label] = [];
    groups[label].push(a);
  });

  return (
    <div className="mb-1">
      <button
        onClick={onToggle}
        className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left hover:bg-slate-800/60 transition-all ${isExpanded ? 'bg-slate-800/40' : ''}`}
      >
        <Icon className={`w-4 h-4 ${domain.color} flex-shrink-0`} />
        <span className="text-sm text-slate-200 flex-1 truncate">{domain.label}</span>
        <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${domain.bg} ${domain.color}`}>{count}</span>
        <ChevronRight className={`w-3.5 h-3.5 text-slate-500 transition-transform ${isExpanded ? 'rotate-90' : ''}`} />
      </button>
      {isExpanded && (
        <div className="ml-4 pl-2 border-l border-slate-800 mt-1 space-y-0.5">
          {Object.entries(groups).map(([groupLabel, items]) => (
            <div key={groupLabel}>
              <p className="text-[10px] font-mono text-slate-500 uppercase tracking-wider px-2 py-1">{groupLabel} ({items.length})</p>
              {items.map(asset => (
                <button
                  key={`${asset.type}-${asset.id}`}
                  onClick={() => onSelectAsset(asset)}
                  className={`w-full flex items-center gap-2 px-2 py-1.5 rounded text-left text-xs transition-all
                    ${selectedAssetId === asset.id ? 'bg-blue-500/10 text-blue-300 border border-blue-500/20' : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'}`}
                >
                  <AssetTypeIcon type={asset.type} className="w-3 h-3 flex-shrink-0" />
                  <span className="truncate">{asset.title}</span>
                </button>
              ))}
            </div>
          ))}
          {count === 0 && <p className="text-[10px] text-slate-600 px-2 py-1 italic">No assets yet</p>}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────
// Relationship Card
// ─────────────────────────────────────────────────

function RelationshipCard({ rel, onApprove, onReject }) {
  const relType = RELATIONSHIP_TYPES.find(r => r.key === rel.relationship_type) || { label: rel.relationship_type, icon: '↔', color: 'text-slate-400' };
  const targetMeta = ASSET_TYPE_META[rel.target_type] || { icon: Database, label: rel.target_type };
  const TargetIcon = targetMeta.icon;

  return (
    <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-3 hover:border-slate-600 transition-all group">
      <div className="flex items-start gap-3">
        <div className="w-8 h-8 rounded-lg bg-slate-700/50 flex items-center justify-center flex-shrink-0 mt-0.5">
          <TargetIcon className="w-4 h-4 text-slate-400" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-sm font-medium text-slate-200 truncate">{rel.target_label || rel.target_id}</span>
            <StatusBadge status={rel.status || 'suggested'} />
          </div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className={`text-[10px] font-mono ${relType.color}`}>{relType.icon} {relType.label}</span>
            <span className="text-slate-600">•</span>
            <ConfidenceBadge score={rel.confidence || 50} />
            {rel.knowledge_domain && <DomainBadge domainKey={rel.knowledge_domain} />}
          </div>
          {rel.description && (
            <p className="text-xs text-slate-500 leading-relaxed">{rel.description}</p>
          )}
        </div>
        {(rel.status === 'suggested' || rel.status === 'pending_review') && (
          <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0">
            <button
              onClick={() => onApprove?.(rel)}
              className="w-6 h-6 rounded-md bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center hover:bg-emerald-500/20 transition-colors"
              title="Approve"
            >
              <Check className="w-3 h-3 text-emerald-400" />
            </button>
            <button
              onClick={() => onReject?.(rel)}
              className="w-6 h-6 rounded-md bg-red-500/10 border border-red-500/20 flex items-center justify-center hover:bg-red-500/20 transition-colors"
              title="Reject"
            >
              <X className="w-3 h-3 text-red-400" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────
// Knowledge Search
// ─────────────────────────────────────────────────

function KnowledgeSearch({ allAssets, onSelectAsset, relationships }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);

  useEffect(() => {
    if (!query.trim()) { setResults([]); return; }
    const q = query.toLowerCase();
    
    // Search by title, type, domain, and tags — plus through relationships
    const directMatches = allAssets.filter(a =>
      a.title.toLowerCase().includes(q) ||
      a.type.toLowerCase().includes(q) ||
      (a.domain || '').toLowerCase().includes(q) ||
      (a.tags || '').toLowerCase().includes(q)
    );

    // Find assets connected to direct matches via relationships
    const directIds = new Set(directMatches.map(a => a.id));
    const connectedIds = new Set();
    relationships.forEach(r => {
      if (directIds.has(r.source_id) && r.status === 'approved') connectedIds.add(r.target_id);
      if (directIds.has(r.target_id) && r.status === 'approved') connectedIds.add(r.source_id);
    });

    const connectedMatches = allAssets.filter(a => connectedIds.has(a.id) && !directIds.has(a.id));

    setResults([
      ...directMatches.map(a => ({ ...a, matchType: 'direct' })),
      ...connectedMatches.map(a => ({ ...a, matchType: 'connected' })),
    ].slice(0, 30));
  }, [query, allAssets, relationships]);

  return (
    <div className="relative">
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
        <input
          type="text"
          value={query}
          onChange={e => setQuery(e.target.value)}
          placeholder='Search all knowledge... try "trust", "HVAC", or "authority"'
          className="w-full bg-slate-800/60 border border-slate-700/50 rounded-xl pl-9 pr-4 py-2.5 text-sm text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/20 transition-all"
        />
      </div>
      {results.length > 0 && (
        <div className="absolute top-full mt-1 left-0 right-0 bg-slate-900 border border-slate-700/50 rounded-xl shadow-2xl z-50 max-h-80 overflow-y-auto">
          {results.map((r, i) => {
            const meta = ASSET_TYPE_META[r.type] || { icon: Database, label: r.type };
            const Icon = meta.icon;
            return (
              <button
                key={`${r.type}-${r.id}-${i}`}
                onClick={() => { onSelectAsset(r); setQuery(''); }}
                className="w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-slate-800/60 transition-colors border-b border-slate-800/50 last:border-0"
              >
                <Icon className="w-4 h-4 text-slate-400 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-slate-200 truncate">{r.title}</p>
                  <p className="text-[10px] text-slate-500">{meta.label} • {KNOWLEDGE_DOMAINS.find(d => d.key === r.domain)?.label || r.domain}</p>
                </div>
                {r.matchType === 'connected' && (
                  <span className="text-[9px] font-mono text-cyan-400 bg-cyan-500/10 px-1.5 py-0.5 rounded">VIA RELATIONSHIP</span>
                )}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────
// Asset Detail Panel (CENTER)
// ─────────────────────────────────────────────────

function AssetDetail({ asset, relationships, allAssets, onRequestAISuggestions, isLoadingAI }) {
  if (!asset) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center">
          <Network className="w-12 h-12 text-slate-700 mx-auto mb-3" />
          <p className="text-sm text-slate-500">Select an asset to view details</p>
          <p className="text-xs text-slate-600 mt-1">or search for knowledge above</p>
        </div>
      </div>
    );
  }

  const meta = ASSET_TYPE_META[asset.type] || { icon: Database, label: asset.type };
  const Icon = meta.icon;
  const domain = KNOWLEDGE_DOMAINS.find(d => d.key === asset.domain);

  // Get relationships where this asset is source or target
  const assetRels = relationships.filter(r =>
    r.source_id === asset.id || r.target_id === asset.id
  );
  const approvedCount = assetRels.filter(r => r.status === 'approved').length;
  const pendingCount = assetRels.filter(r => r.status === 'suggested' || r.status === 'pending_review').length;

  // Find connected AI agents
  const agentRels = assetRels.filter(r =>
    (r.source_type === 'AIAgent' || r.target_type === 'AIAgent') && r.status === 'approved'
  );

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-5">
        <div className="flex items-start gap-4">
          <div className={`w-12 h-12 rounded-xl ${domain?.bg || 'bg-slate-800'} border ${domain?.border || 'border-slate-700'} flex items-center justify-center flex-shrink-0`}>
            <Icon className={`w-6 h-6 ${domain?.color || 'text-slate-400'}`} />
          </div>
          <div className="flex-1 min-w-0">
            <h2 className="text-lg font-bold text-white leading-tight">{asset.title}</h2>
            <div className="flex items-center gap-2 mt-1.5 flex-wrap">
              <span className="text-[10px] font-mono text-slate-500 uppercase">{meta.label}</span>
              <span className="text-slate-700">•</span>
              {domain && <DomainBadge domainKey={domain.key} />}
            </div>
          </div>
        </div>

        {/* Asset info grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">
          <div className="bg-slate-900/50 rounded-lg p-2.5">
            <p className="text-[10px] font-mono text-slate-500 uppercase mb-0.5">Status</p>
            <p className="text-sm text-emerald-400 font-medium">Live</p>
          </div>
          <div className="bg-slate-900/50 rounded-lg p-2.5">
            <p className="text-[10px] font-mono text-slate-500 uppercase mb-0.5">Connections</p>
            <p className="text-sm text-blue-400 font-medium">{approvedCount} approved</p>
          </div>
          <div className="bg-slate-900/50 rounded-lg p-2.5">
            <p className="text-[10px] font-mono text-slate-500 uppercase mb-0.5">Pending</p>
            <p className="text-sm text-amber-400 font-medium">{pendingCount} review</p>
          </div>
          <div className="bg-slate-900/50 rounded-lg p-2.5">
            <p className="text-[10px] font-mono text-slate-500 uppercase mb-0.5">Domain</p>
            <p className={`text-sm font-medium ${domain?.color || 'text-slate-400'}`}>{domain?.label || 'Unclassified'}</p>
          </div>
        </div>

        {/* Tags */}
        {asset.tags && (
          <div className="flex items-center gap-1.5 mt-3 flex-wrap">
            {asset.tags.split(',').map(tag => (
              <span key={tag} className="text-[10px] font-mono text-slate-400 bg-slate-800 px-2 py-0.5 rounded">
                {tag.trim()}
              </span>
            ))}
          </div>
        )}

        {/* AI Agents */}
        {agentRels.length > 0 && (
          <div className="mt-3 pt-3 border-t border-slate-700/50">
            <p className="text-[10px] font-mono text-slate-500 uppercase mb-1.5">AI Agents Using This</p>
            <div className="flex gap-2 flex-wrap">
              {agentRels.map(r => {
                const agentId = r.source_type === 'AIAgent' ? r.source_id : r.target_id;
                const agentLabel = r.source_type === 'AIAgent' ? r.source_label : r.target_label;
                return (
                  <span key={agentId} className="inline-flex items-center gap-1 text-xs text-violet-400 bg-violet-500/10 px-2 py-1 rounded-lg border border-violet-500/20">
                    <Bot className="w-3 h-3" />
                    {agentLabel || agentId}
                  </span>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* AI Suggestions Button */}
      <button
        onClick={() => onRequestAISuggestions(asset)}
        disabled={isLoadingAI}
        className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-blue-600/20 to-purple-600/20 border border-blue-500/30 rounded-xl px-4 py-3 text-sm font-medium text-blue-300 hover:border-blue-400/50 hover:from-blue-600/30 hover:to-purple-600/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isLoadingAI ? (
          <><Loader2 className="w-4 h-4 animate-spin" /> Analyzing connections...</>
        ) : (
          <><Sparkles className="w-4 h-4" /> AI: Find Connections for This Asset</>
        )}
      </button>

      {/* Quick stats */}
      <div className="bg-slate-800/30 border border-slate-700/30 rounded-xl p-3">
        <p className="text-[10px] font-mono text-slate-500 uppercase mb-2">Relationship Summary</p>
        <div className="space-y-1">
          {(() => {
            const typeCounts = {};
            assetRels.forEach(r => {
              const key = r.relationship_type;
              typeCounts[key] = (typeCounts[key] || 0) + 1;
            });
            return Object.entries(typeCounts).map(([type, count]) => {
              const rt = RELATIONSHIP_TYPES.find(r => r.key === type) || { label: type, color: 'text-slate-400', icon: '↔' };
              return (
                <div key={type} className="flex items-center justify-between">
                  <span className={`text-xs ${rt.color}`}>{rt.icon} {rt.label}</span>
                  <span className="text-xs text-slate-500 font-mono">{count}</span>
                </div>
              );
            });
          })()}
          {assetRels.length === 0 && (
            <p className="text-xs text-slate-600 italic">No connections yet — use AI builder above</p>
          )}
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────
// Relationship Graph Panel (RIGHT)
// ─────────────────────────────────────────────────

function RelationshipPanel({ asset, relationships, onApprove, onReject }) {
  const [filter, setFilter] = useState('all'); // all, approved, pending

  if (!asset) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center px-4">
          <GitBranch className="w-10 h-10 text-slate-700 mx-auto mb-2" />
          <p className="text-xs text-slate-500">Relationships appear here</p>
        </div>
      </div>
    );
  }

  const assetRels = relationships.filter(r =>
    r.source_id === asset.id || r.target_id === asset.id
  );

  const filtered = filter === 'all' ? assetRels :
    filter === 'approved' ? assetRels.filter(r => r.status === 'approved') :
    assetRels.filter(r => r.status === 'suggested' || r.status === 'pending_review');

  // Group by relationship type
  const grouped = {};
  filtered.forEach(r => {
    const key = r.relationship_type;
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(r);
  });

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-slate-300">Connections</h3>
        <span className="text-[10px] font-mono text-slate-500">{assetRels.length} total</span>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-1">
        {['all', 'approved', 'pending'].map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`text-[10px] font-mono px-2 py-1 rounded transition-colors capitalize
              ${filter === f ? 'bg-blue-500/10 text-blue-400 border border-blue-500/20' : 'text-slate-500 hover:text-slate-300'}`}
          >
            {f} ({f === 'all' ? assetRels.length :
              f === 'approved' ? assetRels.filter(r => r.status === 'approved').length :
              assetRels.filter(r => r.status === 'suggested' || r.status === 'pending_review').length})
          </button>
        ))}
      </div>

      {/* Grouped relationships */}
      {Object.entries(grouped).map(([type, rels]) => {
        const rt = RELATIONSHIP_TYPES.find(r => r.key === type) || { label: type, icon: '↔', color: 'text-slate-400' };
        return (
          <div key={type}>
            <p className={`text-[10px] font-mono uppercase tracking-wider ${rt.color} mb-1.5`}>
              {rt.icon} {rt.label} ({rels.length})
            </p>
            <div className="space-y-1.5">
              {rels.map((r, i) => (
                <RelationshipCard
                  key={r.id || `${r.target_id}-${i}`}
                  rel={r}
                  onApprove={onApprove}
                  onReject={onReject}
                />
              ))}
            </div>
          </div>
        );
      })}

      {filtered.length === 0 && (
        <div className="text-center py-8">
          <Network className="w-8 h-8 text-slate-700 mx-auto mb-2" />
          <p className="text-xs text-slate-500">
            {filter === 'all' ? 'No connections yet' :
              filter === 'approved' ? 'No approved connections' : 'No pending suggestions'}
          </p>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────
// Knowledge Health Stats
// ─────────────────────────────────────────────────

function KnowledgeHealth({ allAssets, relationships }) {
  const totalAssets = allAssets.length;
  const approvedRels = relationships.filter(r => r.status === 'approved').length;
  const pendingRels = relationships.filter(r => r.status === 'suggested' || r.status === 'pending_review').length;
  const connectedAssets = new Set();
  relationships.filter(r => r.status === 'approved').forEach(r => {
    connectedAssets.add(r.source_id);
    connectedAssets.add(r.target_id);
  });
  const connectionRate = totalAssets > 0 ? Math.round((connectedAssets.size / totalAssets) * 100) : 0;

  const domainCounts = {};
  KNOWLEDGE_DOMAINS.forEach(d => { domainCounts[d.key] = 0; });
  allAssets.forEach(a => {
    if (domainCounts[a.domain] !== undefined) domainCounts[a.domain]++;
  });

  return (
    <div className="space-y-3">
      {/* Stats Row */}
      <div className="grid grid-cols-4 gap-2">
        <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-3 text-center">
          <p className="text-xl font-black text-blue-400">{totalAssets}</p>
          <p className="text-[9px] font-mono text-slate-500 uppercase">Assets</p>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-3 text-center">
          <p className="text-xl font-black text-emerald-400">{approvedRels}</p>
          <p className="text-[9px] font-mono text-slate-500 uppercase">Connected</p>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-3 text-center">
          <p className="text-xl font-black text-amber-400">{pendingRels}</p>
          <p className="text-[9px] font-mono text-slate-500 uppercase">Pending</p>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-3 text-center">
          <p className="text-xl font-black text-cyan-400">{connectionRate}%</p>
          <p className="text-[9px] font-mono text-slate-500 uppercase">Health</p>
        </div>
      </div>

      {/* Domain breakdown bar */}
      <div className="bg-slate-800/30 border border-slate-700/30 rounded-xl p-3">
        <p className="text-[10px] font-mono text-slate-500 uppercase mb-2">Domain Distribution</p>
        <div className="flex h-3 rounded-full overflow-hidden gap-px">
          {KNOWLEDGE_DOMAINS.map(d => {
            const count = domainCounts[d.key] || 0;
            const pct = totalAssets > 0 ? (count / totalAssets) * 100 : 0;
            if (pct === 0) return null;
            return (
              <div
                key={d.key}
                className={`${d.bg} border ${d.border} transition-all`}
                style={{ width: `${pct}%` }}
                title={`${d.label}: ${count} assets (${Math.round(pct)}%)`}
              />
            );
          })}
        </div>
        <div className="grid grid-cols-2 gap-1 mt-2">
          {KNOWLEDGE_DOMAINS.map(d => (
            <div key={d.key} className="flex items-center gap-1.5">
              <div className={`w-2 h-2 rounded-sm ${d.bg} border ${d.border}`} />
              <span className="text-[10px] text-slate-500">{d.label}</span>
              <span className={`text-[10px] font-mono ${d.color} ml-auto`}>{domainCounts[d.key] || 0}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────

export default function KnowledgeNavigator() {
  // State
  const [allAssets, setAllAssets] = useState(STATIC_ASSETS);
  const [relationships, setRelationships] = useState([]);
  const [selectedAsset, setSelectedAsset] = useState(null);
  const [expandedDomains, setExpandedDomains] = useState({});
  const [isLoadingEntities, setIsLoadingEntities] = useState(true);
  const [isLoadingAI, setIsLoadingAI] = useState(false);
  const [view, setView] = useState('navigator'); // navigator | health

  // Load entity-based assets + relationships
  useEffect(() => {
    async function loadAssets() {
      setIsLoadingEntities(true);
      try {
        const entityTypes = [
          { entity: 'BlogPost', type: 'BlogPost', titleField: 'title', domain: 'thought_leadership' },
          { entity: 'KnowledgeArticle', type: 'KnowledgeArticle', titleField: 'article_title', domain: 'education_training' },
          { entity: 'CaseStudy', type: 'CaseStudy', titleField: 'title', domain: 'sales_intelligence' },
          { entity: 'SalesKnowledgeBase', type: 'SalesKnowledgeBase', titleField: 'title', domain: 'sales_intelligence' },
          { entity: 'SOPWorkflow', type: 'SOPWorkflow', titleField: 'name', domain: 'operational_knowledge' },
          { entity: 'ChatbotKnowledge', type: 'ChatbotKnowledge', titleField: 'question', domain: 'market_intelligence' },
          { entity: 'KnowledgeGapSignal', type: 'KnowledgeGapSignal', titleField: 'gap_title', domain: 'operational_knowledge' },
          { entity: 'TopicCluster', type: 'TopicCluster', titleField: 'topic', domain: 'market_intelligence' },
          { entity: 'AIPromptTemplates', type: 'AIPromptTemplates', titleField: 'template_name', domain: 'brand_creative' },
        ];

        const dynamicAssets = [];
        for (const { entity, type, titleField, domain } of entityTypes) {
          try {
            const EntityClass = base44.entities[entity];
            if (!EntityClass) continue;
            const records = await EntityClass.list();
            if (Array.isArray(records)) {
              records.forEach(r => {
                dynamicAssets.push({
                  type,
                  id: r.id,
                  title: r[titleField] || r.title || r.name || `${type} #${r.id}`,
                  domain,
                  tags: r.tags || r.category || '',
                });
              });
            }
          } catch (e) {
            console.warn(`Failed to load ${entity}:`, e);
          }
        }

        // Load relationships
        let rels = [];
        try {
          const KnowledgeRelationship = base44.entities.KnowledgeRelationship;
          if (KnowledgeRelationship) {
            rels = await KnowledgeRelationship.list();
          }
        } catch (e) {
          console.warn('KnowledgeRelationship entity not yet deployed:', e);
        }

        // Merge static + dynamic, dedup by type+id
        const seen = new Set();
        const merged = [];
        [...dynamicAssets, ...STATIC_ASSETS].forEach(a => {
          const key = `${a.type}-${a.id}`;
          if (!seen.has(key)) {
            seen.add(key);
            merged.push(a);
          }
        });

        setAllAssets(merged);
        setRelationships(Array.isArray(rels) ? rels : []);
      } catch (err) {
        console.error('Failed to load knowledge assets:', err);
      }
      setIsLoadingEntities(false);
    }
    loadAssets();
  }, []);

  // Toggle domain expansion
  const toggleDomain = useCallback((domainKey) => {
    setExpandedDomains(prev => ({ ...prev, [domainKey]: !prev[domainKey] }));
  }, []);

  // Select asset
  const selectAsset = useCallback((asset) => {
    setSelectedAsset(asset);
  }, []);

  // AI Suggestions
  const requestAISuggestions = useCallback(async (asset) => {
    setIsLoadingAI(true);
    try {
      const result = await base44.functions.invoke('buildKnowledgeRelationships', {
        asset_type: asset.type,
        asset_id: asset.id,
        asset_title: asset.title,
        asset_domain: asset.domain,
        existing_assets: allAssets.slice(0, 100).map(a => ({
          type: a.type, id: a.id, title: a.title,
          domain: a.domain, tags: a.tags
        }))
      });

      if (result?.suggestions?.length > 0) {
        const newRels = result.suggestions.map(s => ({
          id: `ai-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
          source_type: asset.type,
          source_id: asset.id,
          source_label: asset.title,
          target_type: s.target_type,
          target_id: s.target_id,
          target_label: s.target_label,
          relationship_type: s.relationship_type,
          confidence: s.confidence,
          description: s.reasoning,
          knowledge_domain: asset.domain,
          created_by: 'ai_builder',
          ai_generated: true,
          approved: false,
          status: 'suggested',
          created_date: new Date().toISOString(),
        }));
        setRelationships(prev => [...prev, ...newRels]);
      }
    } catch (err) {
      console.error('AI suggestion error:', err);
    }
    setIsLoadingAI(false);
  }, [allAssets]);

  // Approve / Reject relationship
  const approveRelationship = useCallback(async (rel) => {
    // Save to entity
    try {
      const KnowledgeRelationship = base44.entities.KnowledgeRelationship;
      if (KnowledgeRelationship) {
        await KnowledgeRelationship.create({
          ...rel,
          status: 'approved',
          approved: true,
          last_verified: new Date().toISOString(),
        });
      }
    } catch (e) { console.warn('Could not persist relationship:', e); }

    setRelationships(prev => prev.map(r =>
      r.id === rel.id ? { ...r, status: 'approved', approved: true } : r
    ));
  }, []);

  const rejectRelationship = useCallback((rel) => {
    setRelationships(prev => prev.map(r =>
      r.id === rel.id ? { ...r, status: 'rejected', approved: false } : r
    ));
  }, []);

  return (
    <div className="bg-slate-950 min-h-screen text-slate-200 font-sans">
      {/* Header */}
      <div className="bg-slate-900 border-b border-slate-800 sticky top-0 z-40">
        <div className="max-w-[1600px] mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-600/20 flex items-center justify-center border border-blue-500/30">
              <Network className="w-5 h-5 text-blue-400" />
            </div>
            <div>
              <h1 className="font-bold text-white text-lg leading-tight">Knowledge Navigator™</h1>
              <p className="text-[10px] text-slate-500 font-mono uppercase tracking-wider">K-002 · Connected Knowledge System · R0.3</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setView('navigator')}
              className={`text-xs px-3 py-1.5 rounded-lg transition-colors ${view === 'navigator' ? 'bg-blue-500/10 text-blue-400 border border-blue-500/20' : 'text-slate-400 hover:text-slate-200'}`}
            >
              <Network className="w-3.5 h-3.5 inline mr-1" /> Navigator
            </button>
            <button
              onClick={() => setView('health')}
              className={`text-xs px-3 py-1.5 rounded-lg transition-colors ${view === 'health' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-slate-400 hover:text-slate-200'}`}
            >
              <BarChart3 className="w-3.5 h-3.5 inline mr-1" /> Health
            </button>
          </div>
        </div>
      </div>

      {/* Search */}
      <div className="max-w-[1600px] mx-auto px-4 py-3">
        <KnowledgeSearch
          allAssets={allAssets}
          onSelectAsset={selectAsset}
          relationships={relationships}
        />
      </div>

      {view === 'health' ? (
        <div className="max-w-3xl mx-auto px-4 py-4">
          <KnowledgeHealth allAssets={allAssets} relationships={relationships} />
        </div>
      ) : (
        /* Three-panel layout */
        <div className="max-w-[1600px] mx-auto px-4 pb-8">
          <div className="flex gap-4" style={{ minHeight: 'calc(100vh - 140px)' }}>
            {/* LEFT — Domain Navigator */}
            <div className="w-72 flex-shrink-0">
              <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-3 sticky top-20">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Knowledge Domains</h3>
                  {isLoadingEntities && <Loader2 className="w-3 h-3 text-slate-500 animate-spin" />}
                </div>
                <div className="space-y-0.5">
                  {KNOWLEDGE_DOMAINS.map(domain => (
                    <DomainItem
                      key={domain.key}
                      domain={domain}
                      assets={allAssets}
                      isExpanded={expandedDomains[domain.key] || false}
                      onToggle={() => toggleDomain(domain.key)}
                      onSelectAsset={selectAsset}
                      selectedAssetId={selectedAsset?.id}
                    />
                  ))}
                </div>
              </div>
            </div>

            {/* CENTER — Asset Detail */}
            <div className="flex-1 min-w-0">
              <AssetDetail
                asset={selectedAsset}
                relationships={relationships}
                allAssets={allAssets}
                onRequestAISuggestions={requestAISuggestions}
                isLoadingAI={isLoadingAI}
              />
            </div>

            {/* RIGHT — Relationships + Recommendations */}
            <div className="w-80 flex-shrink-0 space-y-3">
              <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-3 sticky top-20 max-h-[calc(100vh-100px)] overflow-y-auto space-y-3">
                <RelationshipPanel
                  asset={selectedAsset}
                  relationships={relationships}
                  onApprove={approveRelationship}
                  onReject={rejectRelationship}
                />

                {/* I-001 Recommendation Panel */}
                {selectedAsset && (
                  <RecommendationPanel
                    contextType="knowledge"
                    contextDescription={`Viewing knowledge asset: "${selectedAsset.title || selectedAsset.name || 'Untitled'}". Domain: ${selectedAsset.domain || 'unknown'}. Looking for related knowledge and connections.`}
                    currentAssetType={selectedAsset.type || ''}
                    currentAssetId={selectedAsset.id || ''}
                    maxResults={5}
                    compact={true}
                  />
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
